<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="TempModel\**" />
    <Compile Remove="TempServer\**" />
    <EmbeddedResource Remove="TempModel\**" />
    <EmbeddedResource Remove="TempServer\**" />
    <None Remove="TempModel\**" />
    <None Remove="TempServer\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Migrations\JamesDatabaseContextModelSnapshot.orig.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Migrations\InsertData.sql" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Migrations\InsertData.sql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.13.1" />
    <PackageReference Include="HotChocolate.AspNetCore.Authorization" Version="14.0.0" />
    <PackageReference Include="HotChocolate.Data.EntityFramework" Version="14.0.0" />
    <PackageReference Include="HotChocolate.Types.Analyzers" Version="14.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.ServiceModel.Http" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\James.Shared.Server\James.Shared.Server.csproj" />
    <ProjectReference Include="..\..\Shared\James.Shared.csproj" />
    <ProjectReference Include="..\JamesDAL.Imaging\James.Data.Imaging.csproj" />
  </ItemGroup>

</Project>
