<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <GraphQL Remove="OnAccountUpdated.graphql" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="GetAccountByAccountNumber.graphql" />
    <None Remove="AccountNumbersQuery.graphql" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.1" PrivateAssets="all" />
    <PackageReference Include="Radzen.Blazor" Version="4.24.6" />
    <PackageReference Include="strawberryshake.blazor" Version="14.0.0-p.32" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\James.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <GraphQL Update="GetAccountByAccountNumber.graphql">
      <Namespace Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">StrawberryShakeDemo.GraphQL</Namespace>
    </GraphQL>
  </ItemGroup>

  <ItemGroup>
    <GraphQL Update="AccountNumbersQuery.graphql">
      <Namespace Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">StrawberryShakeDemo.GraphQL</Namespace>
    </GraphQL>
  </ItemGroup>

</Project>
