@DataApiBuilderPOC_HostAddress = http://localhost:5080

GET {{DataApiBuilderPOC_HostAddress}}/todos/
Accept: application/json

###

GET {{DataApiBuilderPOC_HostAddress}}/todos/1
Accept: application/json

###
