<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<CompressionEnabled>false</CompressionEnabled>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Auth0.AspNetCore.Authentication" Version="1.4.1" />
    <PackageReference Include="Azure.Identity" Version="1.13.1" />
    <PackageReference Include="Blazored.LocalStorage" Version="4.5.0" />
    <PackageReference Include="Blazorise.Animate" Version="1.6.2" />
    <PackageReference Include="Blazorise.Generator.Features" Version="1.6.2" />
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.1.1" />
    <PackageReference Include="HotChocolate.AspNetCore" Version="14.0.0" />
    <PackageReference Include="HotChocolate.AspNetCore.Authorization" Version="14.0.0" />
    <PackageReference Include="HotChocolate.Data.EntityFramework" Version="14.0.0" />
    <PackageReference Include="HotChocolate.Types.Analyzers" Version="14.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="8.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="8.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting.WindowsServices" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="8.0.1" />
    <PackageReference Include="Radzen.Blazor" Version="5.5.2" />
    <PackageReference Include="Serilog" Version="4.1.0" />
    <PackageReference Include="Serilog.Exceptions" Version="8.4.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="8.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="8.0.4" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
    <PackageReference Include="Serilog.Sinks.MSSqlServer" Version="7.0.2" />
    <PackageReference Include="System.DirectoryServices.AccountManagement" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Data\JamesDAL.Imaging\James.Data.Imaging.csproj" />
    <ProjectReference Include="..\..\Data\JamesDAL.Server\James.Data.Server.csproj" />
    <ProjectReference Include="..\..\James.Shared.Server\James.Shared.Server.csproj" />
    <ProjectReference Include="..\..\JApplicationLog\ApplicationLog.csproj" />
    <ProjectReference Include="..\..\Shared\James.Shared.csproj" />
    <ProjectReference Include="..\Client\JamesWebUI.Client.csproj" />
  </ItemGroup>


</Project>
