<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HotChocolate.AspNetCore" Version="14.0.0-p.35" />
    <PackageReference Include="HotChocolate.Data.EntityFramework" Version="14.0.0-p.35" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Data\JamesDAL.Server\James.Data.Server.csproj" />
    <ProjectReference Include="..\..\Shared\James.Shared.csproj" />
  </ItemGroup>

</Project>
