<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\JApplicationLog\ApplicationLog.csproj" />
    <ProjectReference Include="..\..\Shared\James.Shared.csproj" />
    <ProjectReference Include="..\SharedBusinessLogic\SharedBusinessLogic.csproj" />
  </ItemGroup>

</Project>
