subscription SearchResultReady($searchTerm: String!) {
  onSearchResultReady(searchTerm: $searchTerm) {
    identifier
    result {
      confidence
      fromDescription
      name
      searchString
      type
      accountNum
      agencyNumber
      entity {
        id
        isIndividual
        fullName
        entityType
        legalEntityAddresses {
          type
          address {
            address1
            city
            postalCode
            stateCode
          }
        }
      }
    }
  }
}

query SuperSearch($searchTerm: String!) {
  search(searchTerm: $searchTerm) 
}
