query GetAgencyPOAs($agencyId: UUID!){
    agencyPOAs(agencyId: $agencyId){
        id,
        comments,
        status,
        statusNavigation{
            status
        }
        limit,
        serial,
        currentIssued,
        firstIssued,
        insurerId,
        insurer{
            id,
            fullName,
            idNavigation{
              fullName
            }
        }
        powerOfAttorneyDocumentStatuses{
            id,
            requested,
            received,
            comments,
            documentTypeId,
            documentType{
                name,
                id
            }
        }
    }
}