query agencyAccounts($agencyNumber: String!) {
  agencyAccounts(agencyNumber: $agencyNumber) {
    accountNum
    branch
    idNavigation {
      fullName
    }
    bonds {
      bondNumber
      accountNum
      effective
      expiration
      underWriter {
        idNavigation{
          fullName
        }
      }
      obligee {
        fullName
      }
      bondType {
        bondType
      }
      siccode
      municipality
      bondClass
      status
    }
    mainAddress {
      id
      address1
      address2
      city
      stateCode
      postalCode
    }
  }
}
