query GetAgencyByAgencyNumber($agencyNumber: String!) {
  agencyByAgencyNumber(agencyNumber: $agencyNumber) {
    id
    agencyNumber
    branch
    status
    w9
    nasbp
    nationalProducerNumber
    idNavigation {
      fullName
      parentNavigation {
        id
        fullName
        agencyIdNavigation {
          agencyNumber
        }
      }
      legalEntityAddresses {
        type
        address {
          id
          address1
          address2
          address3
          city
          stateCode
          stateCodeNavigation {
            countryCode
            countryCodeNavigation {
              name
            }
          }
          postalCode
        }
      }
    }
  }
}
