query GetAgencyAgents($agencyId: UUID!){
	agencyAgents(agencyId: $agencyId){
        agentId,
        agent{
            fullName,
            givenName,
            middleInitial,
            familyName,
            mainEmailAddress,
            nationalProducerNumber,
            idNavigation{
                givenName,
                middleInitial,
                familyName,
                fullName
            }
            agencyLicenses{
                id,
                licenseNumber,
                comments,
                appointment,
                termination,
                appointingState,
                state,
                isActive,
                created,
                insurer{
                    id,
                    idNavigation{
                        fullName
                    }
                }
            }
        }
    }
}