query GetAgencyByAgencyNumber($agencyNumber: String!)
{
	agencyByAgencyNumber(agencyNumber:$agencyNumber)
    {
		agencyNumber,
        branch,
        status,
        w9,
        nasbp,
        agents{
            fullName,
            givenName,
            middleInitial,
            familyName,
            mainEmailAddress,
            nationalProducerNumber
        }
		idNavigation
        {
			fullName,
			legalEntityAddresses
            {
				type,
				address
                {
                    address1,
                    address2,
                    address3,
                    city,
                    stateCode,
                    stateCodeNavigation 
                    {
                        countryCode,
                        countryCodeNavigation 
                        {
                            name
                        }     
                    },
                    postalCode
                }
			}
		}
	}
}