namespace JamesWebUI.Client.GraphQL
{
    public partial class JamesClient
    {
        //NOTE:  This class is here simply to stop intellisense putting up warning that this class does not exist.
        //          All the real code is autogenerated by StrawberryShake

        //       If real code ever needs to be added here, bring it up as an architectural change.
        //       IOW, for now don't put any code here.  But if a need comes up where it might make sense, lets talk about it.
    }
}
