<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
    <StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
  </PropertyGroup>

  <ItemGroup>
    <GraphQL Remove="AccountModifiedSubscription.graphql" />
    <GraphQL Remove="UpdateBankMutation.graphql" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="AccountNumbersQuery.graphql" />
    <None Remove="GetAccountByAccountNumber.graphql" />
    <None Remove="schema.graphql" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.1" />
    <PackageReference Include="Radzen.Blazor" Version="4.24.6" />
    <PackageReference Include="StrawberryShake.Blazor" Version="14.0.0-p.32" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Shared\James.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <GraphQL Update="Graphql\AccountNumbersQuery.graphql">
      <Namespace>StrawberryShakeWASM.Client.GraphQL</Namespace>
    </GraphQL>
    <GraphQL Update="Graphql\GetAccountByAccountNumber.graphql">
      <Namespace>StrawberryShakeWASM.Client.GraphQL</Namespace>
    </GraphQL>
  </ItemGroup>

</Project>
