mutation SetAccountCurrentCreditReportLink($input: SetCurrentCreditReportLinkInput!) {
  setCurrentCreditReportLink(input: $input) {
    boolean
  }
}
mutation SetAccountGeneralInfo ($input: SetAccountGeneralInfoInput!){
  setAccountGeneralInfo (input: $input) {
    boolean
  }
} 
mutation SetAccountSystems ($input: SetAccountSystemsInput!){
  setAccountSystems (input: $input) {
    boolean
  }
} 
 mutation SetAccountAdditionalInformation ($input: SetAccountAdditionalInformationInput!){
  setAccountAdditionalInformation (input: $input) {
    boolean
  }
} 
mutation SetAccountProgram($input: SetAccountProgramInput!) {
  setAccountProgram(input: $input) {
    accountProgram {
      accountNum
      aggregate
      approvedBy
      approvedDate
      comments
      created
      createdBy
      effective
      expiration
      homeOfficeApproved
      id
      modified
      single
      statusId
    }
  }
}

mutation CreateAccountWatch($input: CreateAccountWatchInput!) {
    createAccountWatch(input: $input) {
        accountWatch {
            id
            watchDate
            watchStatus
            reason
            actionPlan
        }
    }
}

mutation  UpdateAccountWatch($input: UpdateAccountWatchInput!) {
    updateAccountWatch(input: $input) {
        accountWatch {
            id
            watchDate
            watchStatus
            reason
            actionPlan
        }
    }
}

mutation DeleteAccountWatch($input: DeleteAccountWatchInput!) {
    deleteAccountWatch(input: $input) {
        boolean
    }
}

mutation SetAccountCommercialInfo($input: SetAccountCommercialInfoInput!) {
    setAccountCommercialInfo(input: $input){
        boolean
    }
}

mutation SetAccountAgencyAndAgent($input: SetAccountAgencyAndAgentInput!) {
    setAccountAgencyAndAgent(input: $input) {
        boolean
    }
}

mutation SetAccountGeneralInfoPanel($input: SetAccountGeneralInfoPanelInput!) {
    setAccountGeneralInfoPanel(input: $input){
        boolean
    }
}

mutation SetCreditReport($input: SetCreditReportInput!) {
    setCreditReport(input: $input) {
        boolean
    }
}

mutation DeleteCreditReport($input: DeleteCreditReportInput!) {
    deleteCreditReport(input: $input) {
        boolean
    }
}