mutation SetAccountCurrentCreditReportLink($input: SetCurrentCreditReportLinkInput!) {
  setCurrentCreditReportLink(input: $input) {
    boolean
  }
}
mutation SetAccountGeneralInfo ($input: SetAccountGeneralInfoInput!){
  setAccountGeneralInfo (input: $input) {
    boolean
  }
} 
mutation SetAccountProgram($input: SetAccountProgramInput!) {
  setAccountProgram(input: $input) {
    accountProgram {
      accountNum
      aggregate
      approvedBy
      approvedDate
      comments
      created
      createdBy
      effective
      expiration
      homeOfficeApproved
      id
      modified
      single
      statusId
    }
  }
} 
