mutation CreateAddress($input: CreateAddressInput!){
  createAddress (input: $input){
    boolean
  }
} 

mutation DeleteAddress ($input: DeleteAddressInput!) {
  deleteAddress (input: $input) {
    boolean
  }
}

mutation CreatePhoneNumber($input: CreatePhoneNumberInput!) {
	createPhoneNumber(input: $input) {
	boolean
	}
}
mutation DeletePhoneNumber($input: DeletePhoneNumberInput!) {
	deletePhoneNumber(input: $input) {
	boolean
	}
}

mutation SetEmailAddress($input: SetLegalEntityEmailInput!) {
    setLegalEntityEmail(input: $input) {
        legalEntityEmail {
            emailAddress
            id
            legalEntityId
            type
            legalEntity {
                fullName
            }
        }
    }
}

mutation DeleteEmailAddress($input: DeleteLegalEntityEmailInput!) {
    deleteLegalEntityEmail(input: $input) {
        boolean
    }
}