mutation AccountProgramChangeStatus($input: AccountProgramChangeStatusInput!) {
    accountProgramChangeStatus(input: $input) {
        boolean
    }
}

mutation SetAccountProgram($input: SetAccountProgramInput!) {
    setAccountProgram(input: $input) {
        boolean
    }
}

mutation DeleteAccountProgram($id: UUID!) {
    deleteAccountProgram(input: {accountProgramId: $id}) {
        boolean
    }
}

mutation SetLoaLog($input: SetLoaLogInput!) {
    setLoaLog(input: $input) {
        boolean
    }
}

mutation LoaLogDelete($input: LoaLogDeleteInput!) {
    loaLogDelete(input: $input) {
        boolean
    }
}

mutation LoaLogChangeStatus($input: LoaLogChangeStatusInput!) {
    loaLogChangeStatus(input: $input) {
        boolean
    }
}

mutation SetAgencyLoa($input: SetAgencyLoaInput!){
    setAgencyLoa(input: $input) {
        boolean
    }
}

mutation AgencyLoaDelete($input: AgencyLoaDeleteInput!) {
    agencyLoaDelete(input: $input) {
        boolean
    }
}


