mutation UpdateNotificationProperty($id: UUID!, $name: String!, $type: String!) {
    updateNotificationProperty(input: {id: $id, name: $name, type: $type}){
        boolean
    }
}

mutation UpdateNotification($id: UUID!, $accountId: UUID, $agencyId: UUID, $body: String!,
    $followUpDate: DateTime, $properties: [NotificationPropertyValueInput!]!,
    $recipients: [NotificationRecipientInput!]!, $sendEmail: Boolean!, $sendSms: Boolean!,
    $status: String!, $title: String!, $senderUserEmail: String!, $senderUserId: UUID) {
    updateNotification(input: {id: $id, accountId: $accountId, agencyId: $agencyId, body: $body,
        followUpDate: $followUpDate, properties: $properties, recipients: $recipients, sendEmail: $sendEmail, 
        sendSms: $sendSms, senderUserId: $senderUserId, senderUserEmail: $senderUserEmail, status: $status, 
        title: $title}){
        boolean
    }
}

mutation DeleteNotification($id: UUID!){
    deleteNotification(input: {id: $id}){
        boolean
    }
}

mutation DeleteNotificationProperty($id: UUID!){
    deleteNotificationProperty(input: {id: $id}){
        boolean
    }
}