query GetAccountByNumber($accountNumber: String) {
  accountByNumber(accountNumber: $accountNumber) {
      id
      idNavigation {
          fullName
          legalEntityAddresses {
              type
              address {
                  address1
                  address2
                  address3
                  city
                  stateCode
                  stateCodeNavigation {
                      countryCode
                      countryCodeNavigation {
                          name
                      }
                  }
                  postalCode
              }
          }
          legalEntityPhones {
              type
              phoneNumber {
                  mainNumber
                  extension
              }
          }
          legalEntityEmails {
              type
              emailAddress
          }
      }
      bank
      agent {
          idNavigation {
              fullName
              legalEntityEmails {
                  id
                  type
                  emailAddress
              }
          }
          emailAddresses {
              id
              type
              emailAddress
          }
          mainEmailAddress
      }
      agencyNumberNavigation {
          idNavigation {
              fullName
              legalEntityAddresses {
                  type
                  address {
                      city
                      stateCode
                      address1
                      address2
                      address3
                      country
                      countryCode
                      id
                      postalCode
                      state
                  }
              }
          }
      }
      accountWatches {
          id
          actionPlan
          reason
          watchDate
          watchStatus
      }
      accountNum
      division
      homeOfficeReviewByNavigation {
          fullName
      }
      homeOfficeReviewed
      branchReviewByNavigation {
          fullName
      }
      branchReviewed
      attorney {
          idNavigation {
              fullName
          }
          martindaleHubbellRating
      }
      underwriterId
      underwriter {
          idNavigation {
              fullName
              initials
              title
              email
          }
          reportsTo
      }
      branch
      branchNavigation {
          id
          branchKey
          name
      }
      divisionNavigation {
          id
          divisionCode
          division
      }
      accountStatusLogs {
          accountStatus
          effective
          id
      }
      bankPhone {
          countryCode
          created
          extension
          id
          mainNumber
          modified
      }
      cpafirm {
          created
          entityType
          familyName
          fullName
          givenName
          id
          isIndividual
          middleInitial
          modified
          parent
          taxIdEncrypted
          website
          legalEntityPhones {
              legalEntityId
              phoneNumberId
              type
          }
      }
      cpacontact {
          created
          entityType
          familyName
          fullName
          givenName
          id
          isIndividual
          middleInitial
          modified
          parent
          taxIdEncrypted
          website
      }
      businessTypeNavigation {
          businessType
          created
          id
          modified
      }
      businessTypeClassNavigation {
          businessType
          classCode
          created
          id
          isContract
          modified
      }
      lawFirm {
          comment
          idNavigation {
              fullName
          }
          martindaleHubbellRating
      }
      indemnitors {
          id
          agreementDate
      }
      yearOpened
      currentManagementYear
      creditReport
      interimWips
      indemnityPerson
      indemnityFull
      indemnityCorp
      indemnityComments
      priorSuretyCompany
      subcontractPercent
      subcontractProtection
      taxBasis
      continuityActiveMultipleOwners
      continuityFundedBuySell
      continuityKeyManagementLifeInsurance
      continuityManagementIncentives
      businessType
      businessTypeClass
      estimatingSignoff
      estimatingSystem
      accountingSystem
      affiliateCompany
      bankAverageBalance
      bankLastContacted
      bankLoc
      bankLocexpires
      bankLochigh
      bankLochighDate
      bankLocsecurity
      bankLocused
      bankReferenceName
      berkleyAffiliate
  }
}

query SearchAccounts($input: String!) {
  searchAccounts(searchString: $input) {
    accountNum
    idNavigation {
      fullName
      legalEntityAddresses {
        type
        address {
          address1
          address2
          address3
          city
          stateCode
          stateCodeNavigation {
            countryCode
            countryCodeNavigation {
              name
            }
          }
          postalCode
        }
      }
      legalEntityPhones {
        type
        phoneNumber {
          mainNumber
          extension
        }
      }
      legalEntityEmails {
        type
        emailAddress
      }
    }
  }
}

query GetAccountActiveLinesOfAuthority($input: String!) {
  accountActiveLinesOfAuthority(accountNumber: $input) {
    accountNum
    commercialLOA {
      accountNum
      approved
      approvedBy
      bondType
      comments
      conditions
      created
      createdBy
      division
      effective
      expiration
      homeOfficeApproved
      id
      loaaggregate
      loasingle
      modified
      sequenceNumber
      status
    }
    contractLOA {
      accountNum
      approved
      approvedBy
      bondType
      comments
      conditions
      created
      createdBy
      division
      effective
      expiration
      homeOfficeApproved
      id
      loaaggregate
      loasingle
      modified
      sequenceNumber
      status
    }
  }
} 

query GetAccountProgramHistory($input: String!) {
  accountProgramHistory(accountNumber: $input) {
    accountNum
    aggregate
    approvedBy
    approvedDate
    comments
    created
    createdBy
    effective
    expiration
    homeOfficeApproved
    id
    modified
    single
    statusId
    accountProgramStatusHistories {
      accountProgramId
      accountNum
      created
      id
      modified
      newAggregate
      newSingle
      newStatus
      oldAggregate
      oldSingle
      oldStatus
      statusChangeBy
      statusDate
    }
  }
} 
query GetAdditionalRelatedParties($input: String!) {
  additionalRelatedParties(accountNumber: $input) {
    accountNum
    comments
    created
    financialStatements
    guarantor
    id
    indemnity
    modified
    idNavigation {
      created
      entityType
      fullName
      isIndividual
      modified
      parent
    }
  }
}

query GetIdAccountNumbers {
  idAccountNumbers {
      id
      accountNum
  }
}

query GetAllAccountWatches($input: UUID!) {
    allAccountWatches(accountId: $input){
        actionPlan
        id
        reason
        watchDate
        watchStatus
    }
}
