query GetAccountByNumber($accountNumber: String) {
    accountByNumber(accountNumber: $accountNumber) {
        id
        accountNum
        idNavigation {
            fullName
            legalEntityAddresses {
                type
                address {
                    address1
                    address2
                    address3
                    city
                    countryCode
                    country
                    stateCode
                    state
                    postalCode
                    id
                }
            }
            legalEntityEmails {
                type
                emailAddress
                id
            }
            legalEntityPhones {
                type
                phoneNumber {
                    countryCode
                    mainNumber
                    formatted
                    extension
                    id
                }
            }
            mainAddress {
                address1
                address2
                address3
                city
                countryCode
                country
                stateCode
                state
                postalCode
                id
            }
            mainEmail
            mainPhoneNumber {
                id
                countryCode
                mainNumber
                formatted
                extension
            }
            parent
            website
        }
        agencyNumber
        agency {
            id
            agencyNumber
            idNavigation {
                fullName
            }
        }
        agentId
        agent {
            id
            nationalProducerNumber
            fullName
        }
        underwriterId
        underwriter {
            id
            idNavigation {
                fullName
            }
        }
        division
        branch
        branchReviewByNavigation {
            id
            fullName
        }
        bank
        bankPhone {
            id
            countryCode
            mainNumber
            extension
        }
        cpafirm {
            id
            fullName
            legalEntityPhones {
                type
                phoneNumber {
                    countryCode
                    mainNumber
                    extension
                    id
                }
            }
        }
        businessType
        businessTypeClass
        businessTypeClassNavigation {
            isContract
        }
        lawFirm {
            id
            fullName
            idNavigation {
                fullName
            }
        }
        accountStatusLogs {
            effective
            accountStatus
            accountStatusNavigation {
                active
            }
        }
        priorSuretyCompany
        industryCode
        sharedSurety
        fiscalYearEnd
    }
}

query SearchAccounts($input: String!) {
    searchAccounts(searchString: $input) {
        accountNum
        idNavigation {
            fullName
            legalEntityAddresses {
                type
                address {
                    address1
                    address2
                    address3
                    city
                    stateCode
                    stateCodeNavigation {
                        countryCode
                        countryCodeNavigation {
                            name
                        }
                    }
                    postalCode
                }
            }
            legalEntityPhones {
                type
                phoneNumber {
                    mainNumber
                    extension
                }
            }
            legalEntityEmails {
                type
                emailAddress
            }
        }
    }
}

query GetAccountActiveLinesOfAuthority($input: String!) {
    accountActiveLinesOfAuthority(accountNumber: $input) {
        accountNum
        commercialLOA {
            accountNum
            approved
            approvedBy
            bondType
            comments
            conditions
            division
            effective
            expiration
            homeOfficeApproved
            id
            loaaggregate
            loasingle
            sequenceNumber
            status
        }
        contractLOA {
            accountNum
            approved
            approvedBy
            bondType
            comments
            conditions
            division
            effective
            expiration
            homeOfficeApproved
            id
            loaaggregate
            loasingle
            sequenceNumber
            status
        }
    }
}

query GetAccountProgramHistory($input: String!) {
    accountProgramHistory(accountNumber: $input) {
        accountNum
        aggregate
        approvedBy
        approvedDate
        comments
        effective
        expiration
        homeOfficeApproved
        id
        single
        statusId
        accountProgramStatusHistories {
            accountProgramId
            accountNum
            id
            newAggregate
            newSingle
            newStatus
            oldAggregate
            oldSingle
            oldStatus
            statusChangeBy
            statusDate
        }
    }
}
query GetAdditionalRelatedParties($input: String!) {
    additionalRelatedParties(accountNumber: $input) {
        accountNum
        comments
        financialStatements
        guarantor
        id
        indemnity
        idNavigation {
            entityType
            fullName
            isIndividual
            parent
        }
    }
}

query GetIdAccountNumbers {
    idAccountNumbers {
        id
        accountNum
    }
}

query GetFirstIndemnity($input: String!) {
    firstIndemnity(accountNum: $input)
}

query GetAccountAlerts($input1: Int!, $input2: String!) {
    accountAlerts(period: $input1, accountNum: $input2){
        claims {
            bondNumber
            classCode
            claimId
        },
        alerts {
            date
            type
            alert
            link
        }
    }
}

query GetAllAccountWatches($input: String!) {
    allAccountWatches(accountNum: $input){
        actionPlan
        id
        reason
        watchDate
        watchStatus
    }
}

query GetLastPrivateEquityByAccount($input: String!) {
    lastPrivateEquityByAccount(accountNum: $input) {
        created
        enteredBy
        enteredByNavigation {
            fullName
        }
        firmName
        year
    }
}

query GetLastIndemnitorByAccount($input: String!){
    lastIndemnitorByAccount(accountNum: $input){
        executionDate
    }
}

query GetAccountAnnualPremiums($accountNum: String!, $type: String!){
    accountAnnualPremiums(accountNum: $accountNum, type: $type){
        trailingTwelveMonths
        yearToDate
    }
}