query GetAgencyByAgencyNumber($agencyNumber: String!) {
  agencyByAgencyNumber(agencyNumber: $agencyNumber) {
    id
    agencyNumber
    branch
    status
    w9
    nasbp
    profitSharing
    profitSharingMinimumPremium
    nationalProducerNumber
    idNavigation {
      fullName
      parentNavigation {
        id
        fullName
        agencyIdNavigation {
          agencyNumber
        }
      }
      legalEntityAddresses {
        type
        address {
          id
          address1
          address2
          address3
          city
          stateCode
          stateCodeNavigation {
            countryCode
            countryCodeNavigation {
              name
            }
          }
          postalCode
        }
      }
    }
  }
}

query GetAgencyNameAndNumberById($agencyId: UUID!) {
  agencyById(agencyId: $agencyId) {
    agencyNumber
    idNavigation {
      fullName
    }
  }
}

query agencyAccounts($agencyNumber: String!) {
  agencyAccounts(agencyNumber: $agencyNumber) {
      accountNum
      name
      branch
      branchFullName
      status
      bonds {
          bondNumber
          effective
          expiration
          underwriterId
          underwriterFullName
          obligeeId
          obligeeFullName
          bondType 
          siccode
          municipality
          bondClass
          status
          amount
      }
      mainAddress {
          id
          address1
          address2
          address3
          city
          stateCode
          postalCode
          country
          countryCode
          state
      }
  }
}

query agencyAccountBonds($accountNum: String!) {
    agencyAccountBonds(accountNum: $accountNum) {
        bondNumber
        bondType
        amount
        bondClass
        effective
        expiration
        municipality
        obligeeId
        obligeeFullName
        siccode
        status
        underwriterId
        underwriterFullName
    }
}

query GetAgencyBonds($agencyId: UUID!) {
  agencyBonds(agencyId: $agencyId) {
    bondNumber
    accountNumNavigation{
      accountNum
      idNavigation{
        fullName
      }
      
    }
    effective
    expiration
    underWriter{
      idNavigation{
        fullName
      }
    }
    obligee{
      fullName
    }
    bondType {
      bondType
    }
    siccode
    municipality
    bondClass
    status
  }
}

query GetAgencyAgents($agencyId: UUID!){
	agencyAgents(agencyId: $agencyId){
        id
        fullName
        givenName
        middleInitial
        familyName
        mainEmailAddress
        nationalProducerNumber
        idNavigation{
            givenName
            middleInitial
            familyName
            fullName
            legalEntityEmails {
                id
                type
                emailAddress
            }
        }
        agencyLicenses{
            id
            licenseNumber
            comments
            appointment
            termination
            appointingState
            state
            isActive
            created
            insurer{
                id
                idNavigation{
                    fullName
                }
            }
        }
    }
}

query GetAgencyCommissionRates($agencyId: UUID!){
    agencyCommissionRates(agencyId: $agencyId){
        agencyId
        bondType
        effective
        expires
        id
        maximum
        minimum
        rate
    }
}

query GetAgencyStatuses{
	agencyStatuses{
		id,
		status
	}
}

query GetAgencyStatusLog($agencyNumber: String!){
  agencyStatusLog (agencyNumber: $agencyNumber){
    agencyNumber
    changedByNavigation{
      id,
      initials,
      fullName
    }
    comments
    created
    effective
    id
    modified
    newStatus
    oldStatus
  }
} 

query GetAgencyLicenses($agencyId: UUID!) {
  agencyLicenses(agencyId: $agencyId) {
    id
    isActive
    state
    appointingState
    licenseNumber
    isResident
    insurerId
    appointment
    expiration
    termination
    insurer {
      id
      idNavigation {
        fullName
      }
    }
    agency {
      agencyNumber
    }
    imagingId
  }
}

query GetAgencyInventory($agencyId: UUID!){
    agencyInventory(agencyId: $agencyId){
        id
        sent
        quantity
        documentType
        addressee
        address{
            address1
            address2
            address3
            city
            stateCode
            postalCode
        }
    }
}

query GetAgencyPOAs($agencyId: UUID!) {
  agencyPOAs(agencyId: $agencyId) {
    id
    comments
    status
    limit
    referenceNumber
    currentIssued
    firstIssued
    insurerId
    imagingId
    insurer {
      id
      fullName
      idNavigation {
        fullName
      }
      defaultRateGroup
    }
    powerOfAttorneyDocumentStatuses {
      id
      requested
      received
      comments
      documentTypeId
      documentType {
        name
        id
      }
    }
    agency {
      agencyNumber
    }
  }
}

query GetAgencyRelatedParties($input: UUID!){
  agencyRelatedParties (agencyId: $input) {
      agencyNumber
      id
      idNavigation {
          fullName
          legalEntityAddresses {
              addressId
              legalEntityId
              type
              address {
                  address1
                  address2
                  address3
                  city
                  postalCode
                  stateCode
              }
          }
      }
  }
}

query GetAllPoaStatuses{
  allPoaStatuses {
    id,
    status
  }
} 

query GetPOADocumentNames{
  poaDocumentNames {
    created
    id
    modified
    name
  }
}
  
query GetIdAgencyNumbers {
  idAgencyNumbers {
    id
    agencyNumber
  }
}

query GetAllActiveAgencies {
    allActiveAgencies {
        fullName
        id
            emails {
            id
            type
            emailAddress
        }
        addresses {
            id
            type
            address1
            address2
            address3
            city
            postalCode
            stateCode
            countryCode
        }
    }
}
