query GetAgencyByAgencyNumber($agencyNumber: String!) {
    agencyByAgencyNumber(agencyNumber: $agencyNumber) {
        id
        agencyNumber
        branch
        status
        w9
        nasbp
        profitSharing
        profitSharingMinimumPremium
        nationalProducerNumber
        agentsInAgencies{
            agentId
            agent {
                idNavigation {
                    fullName
                }
            }
        }
        idNavigation {
            fullName
            parentNavigation {
                id
                fullName
                agencyIdNavigation {
                    agencyNumber
                }
            }
            legalEntityAddresses {
                type
                address {
                    id
                    address1
                    address2
                    address3
                    city
                    stateCode
                    stateCodeNavigation {
                        countryCode
                        countryCodeNavigation {
                            name
                        }
                    }
                    postalCode
                }
            }
            legalEntityEmails {
                type
                emailAddress
            }
        }
    }
}

query GetAgencyNameAndNumberById($agencyId: UUID!) {
  agencyById(agencyId: $agencyId) {
    agencyNumber
    idNavigation {
      fullName
    }
  }
}

query agencyAccounts($agencyNumber: String!) {
  agencyAccounts(agencyNumber: $agencyNumber) {
      accountNum
      branch
      name
      branchFullName
      status
      mainAddress {
          address1
          address2
          address3
          city
          postalCode
          stateCode
      }  
  }
}

query agencyAccountBonds($accountNum: String!) {
    agencyAccountBonds(accountNum: $accountNum) {
        bondNumber
        bondType
        amount
        bondClass
        effective
        expiration
        municipality
        obligeeId
        obligeeFullName
        siccode
        status
        underwriterId
        underwriterFullName
        appointment
        termination
    }
}

query GetAgencyBonds($agencyId: UUID!, $accountNum: String, $skip: Int!, $take: Int!) {
  agencyBonds(agencyId: $agencyId, accountNum: $accountNum, skip: $skip, take: $take) {
      accountName
      accountNum
      beginDate
      bondClass
      bondNumber
      bondType
      branch
      endDate
      obligeeId
      obligeeName
      sicCode
      status
      underWriterId
      underWriterName
      amount
  }
}

query GetAgencyBondsCount($agencyId: UUID!) {
    agencyBondsCount(agencyId: $agencyId) {
        count
    }
}

query GetAgencyAgents($agencyId: UUID!){
	agencyAgents(agencyId: $agencyId){
        id
        agencyId
        agencyName
        agencyNum
        agentId
        fullName
        givenName
        middleInitial
        familyName
        email
        countryCode
        phoneNumber
        extension        
        nationalProducerNumber
        aif
    }
}

query GetAgencyAgentLicenses($agencyId: UUID!, $agentId: UUID!){
    agencyAgentLicenses(agencyId: $agencyId, agentId: $agentId) {
        id
        appointingState
        appointment
        comments
        expiration
        isActive
        isResident
        licenseNumber
        state
        termination
        imagingId
        insurerId
        insurer {
            idNavigation {
                fullName
            }
        }
    }
}

query GetAgencyCommissionRates($agencyId: UUID!){
    agencyCommissionRates(agencyId: $agencyId){
        agencyId
        bondType
        effective
        id
        maximum
        minimum
        rate
    }
}

query GetAgencyStatuses{
	agencyStatuses{
		id,
		status
	}
}

query GetAgencyStatusLog($agencyNumber: String!){
  agencyStatusLog (agencyNumber: $agencyNumber){
    agencyNumber
    changedByNavigation{
      id,
      initials,
      fullName
    }
    comments
    created
    effective
    id
    modified
    newStatus
    oldStatus
  }
} 

query GetAgencyLicenses($agencyId: UUID!, $agents: Boolean!) {
  agencyLicenses(agencyId: $agencyId, agents: $agents) {
    id
    isActive
    state
    appointingState
    licenseNumber
    isResident
    insurerId
    appointment
    expiration
    termination
    insurer {
      id
      idNavigation {
        fullName
      }
    }
    agency {
      agencyNumber
    }
      agent {
          idNavigation {
              fullName
          }
      }
    imagingId
  }
}

query GetAgencyInventory($agencyId: UUID!){
    agencyInventory(agencyId: $agencyId){
        id
        sent
        quantity
        documentType
        addressee
        address{
            address1
            address2
            address3
            city
            stateCode
            postalCode
        }
        approverNavigation {
            fullName
        }
    }
}

query GetAgencyPOAs($agencyId: UUID!, $statusFilter: String!) {
    agencyPOAs(agencyId: $agencyId, statusFilter: $statusFilter) {
        id
        comments
        status
        limit
        referenceNumber
        currentIssued
        firstIssued
        insurerId
        imagingId
        insurer {
            id
            fullName
            idNavigation {
                fullName
            }
            defaultRateGroup
        }
        powerOfAttorneyDocumentStatuses {
            id
            requested
            received
            comments
            documentTypeId
            documentType {
                name
                id
            }
        }
        agency {
            agencyNumber
        }
    }
}

query GetAgencyRelatedParties($input: UUID!){
  agencyRelatedParties (agencyId: $input) {
      isTopParent
      agency {
          agencyNumber
          id
          idNavigation {
              fullName
              legalEntityAddresses {
                  addressId
                  legalEntityId
                  type
                  address {
                      address1
                      address2
                      address3
                      city
                      postalCode
                      stateCode
                  }
              }
          }
      }
  }
}

query GetAllPoaStatuses{
  allPoaStatuses {
    id,
    status
  }
} 

query GetPOADocumentNames{
  poaDocumentNames {
    created
    id
    modified
    name
  }
}
  
query GetIdAgencyNumbers {
  idAgencyNumbers {
    id
    agencyNumber
  }
}

query GetAllActiveAgencies {
    allActiveAgencies {
        id
        agencyNumber
        fullName
        status
    }
}

query GetAgencyList {
    agencyList {
        id
        code
        name
        label
    }
}