query GetAddress($addressId: UUID!){
  address(addressId: $addressId){
    id
    address1
    address2
    address3
    city
    stateCode
    postalCode
  }
}

query GetAllInventoryDocTypes {
  allInventoryDocTypes {
    documentType
    id
  }
}

query GetUserProfileByUserName($userName: String!){
    userProfileByUserName(userName: $userName){
        id
        username
        fullName
        initials
    }
}

query GetAllBranches{
  allBranches {
    active
    bccreceiver
    branchKey
    branchOfficeAddressId
    created
    emailReceiver
    generalLedgerCode
    headCount
    homeOffice
    id
    modified
    name
    phoneId
    region
  }
}

query GetAllLegalEntityAddresses($input: UUID!) {
  allLegalEntityAddresses (legalEntityId: $input) {
    address1
    address2
    address3
    city
    country
    countryCode
    created
    id
    modified
    postalCode
    state
    stateCode
    legalEntityAddress{
      type
    }
  }
} 

query GetAddressTypes{
  addressTypes {
    created
    id
    modified
    order
    type
  }
}