query GetAddress($addressId: UUID!){
    address(addressId: $addressId){
        id
        address1
        address2
        address3
        city
        stateCode
        postalCode
    }
}

query GetAllInventoryDocTypes {
    allInventoryDocTypes {
        documentType
        id
    }
}

query GetAllBranches{
    allBranches {
        active
        bccreceiver
        branchKey
        branchOfficeAddressId
        emailReceiver
        generalLedgerCode
        headCount
        homeOffice
        id
        name
        phoneId
        region
    }
}

query GetDivisions{
    divisions {
        id
        active
        divisionCode
        division
    }
}

query GetAllLegalEntityAddresses($input: UUID!) {
    allLegalEntityAddresses (legalEntityId: $input) {
        address1
        address2
        address3
        city
        country
        countryCode
        id
        postalCode
        state
        stateCode
        legalEntityAddress{
            type
        }
    }
}

query GetAddressTypes{
    addressTypes {
        id
        order
        type
    }
}

query GetPhoneNumber($input: UUID!) {
    phoneNumber(phoneId: $input) {
        countryCode
        extension
        id
        mainNumber
        legalEntityPhone {
            legalEntityId
            phoneNumberId
            type
        }
    }
}
query GetPhoneTypes {
    phoneTypes {
        id
        order
        type
    }
}
query GetAllLegalEntityPhoneNumbers($input: UUID!) {
    allLegalEntityPhoneNumbers(legalEntityId: $input) {
        countryCode
        extension
        id
        mainNumber
        legalEntityPhone {
            type
        }
    }
}

query GetAllCountries {
    allCountries {
        abbreviation
        active
        code
        name
        phoneCode
        phoneMask
        postalCodeMask
    }
}

query GetUserSettings {
    userSettings {
        key
        value
    }
}

query GetEmployees($activeOnly: Boolean!) {
    employees(activeOnly: $activeOnly) {
        id
        active
        activeDirectoryAccount
        fullName
        title
        primaryBranchId
        initials
        email
        homeOfficeApprover
        underwriterIdNavigation {
            active
            notificationSendTo
            reportsToNavigation {
                id
                fullName
            }
        }
    }
}

query GetActiveDirectoryUsers($usernameSearchText: String!) {
    activeDirectoryUsers(searchText: $usernameSearchText) {
        emails
        fullName
        initials
        username
        title
    }
}

mutation SetEmployeeEmail($input: SetEmployeeEmailInput!) {
    setEmployeeEmail(input:$input){
        boolean
    }
}

mutation CreateEmployee($input:CreateEmployeeInput!) {
    createEmployee(input: $input){
        boolean
    }
}

query GetEmployeeByUserName($userName: String!){
    employeeByUserName(userName: $userName){
        id
        activeDirectoryAccount
        fullName
        initials
    }
}

query GetUnderwriters{
    underwriters {
        id
        idNavigation {
            initials
            fullName
        }
    }
}

query GetAllLegalEntityEmails($input: UUID!){
    allLegalEntityEmails(legalEntityId: $input) {
        emailAddress
        id
        legalEntityId
        type
    }
}

query GetAllWatchStatuses {
    allWatchStatuses {
        id
        watchStatus
    }
}

query GetAllEmailTypes {
    emailTypes {
        id
        type
    }
}

query GetAllBusinessTypes {
    allBusinessTypes {
        businessType
    }
}

query GetAllBusinessTypeClassCodes {
    allBusinessTypeClassCodes {
        businessType
        classCode
        isContract
    }
}

query GetAllSicCodes {
    allSicCodes {
        code
        name
    }
}

query GetAllIndustryCodes {
    allIndustryCodes {
        code
        industry
    }
}

query GetAccountLOAs($input: String!) {
    accountLOAs(accountNum: $input) {
        accountLOAs {
            aggregate
            bondType
            effective
            expiration
            single
            status
        }
        agencyLOAs {
            aggregate
            bondType
            effective
            expiration
            single
            status
        },
        loaTotal
    }
}

query GetAllContractRates {
    allContractRates {
        id
        class
        rateGroup
        premiumRate
        rateType
        minumumAmount
        maximumAmount
    }
}


query GetAllCommercialRates {
    allCommercialRates {
        amountPerUnit
        annualMinimum
        commercialBondType
        maximumAmount
        minumumAmount
        rateGroup
        riskType
        unitSize
    }
}

query GetAllRateGroups {
    allRateGroups {
        id
        rateGroup
    }
}

query GetAllRiskTypes {
    allRiskTypes {
        id
        riskType
    }
}

query GetAllCommercialBondTypes {
    allCommercialBondTypes {
        id
        commercialBondType
    }
}