query GetAddress($addressId: UUID!){
  address(addressId: $addressId){
    id
    address1
    address2
    address3
    city
    stateCode
    postalCode
  }
}

query GetAllInventoryDocTypes {
  allInventoryDocTypes {
    documentType
    id
  }
}

query GetEmployeeByUserName($userName: String!){
    employeeByUserName(userName: $userName){
        id
        activeDirectoryAccount
        fullName
        initials
    }
}

query GetAllBranches{
  allBranches {
    active
    bccreceiver
    branchKey
    branchOfficeAddressId
    created
    emailReceiver
    generalLedgerCode
    headCount
    homeOffice
    id
    modified
    name
    phoneId
    region
  }
}

query GetAllLegalEntityAddresses($input: UUID!) {
  allLegalEntityAddresses (legalEntityId: $input) {
    address1
    address2
    address3
    city
    country
    countryCode
    created
    id
    modified
    postalCode
    state
    stateCode
    legalEntityAddress{
      type
    }
  }
} 

query GetAddressTypes{
  addressTypes {
    created
    id
    modified
    order
    type
  }
}

query GetPhoneNumber($input: UUID!) {
	phoneNumber(phoneId: $input) {
	    countryCode
	    created
	    extension
	    id
	    mainNumber
	    modified
	    legalEntityPhone {
		    legalEntityId
		    phoneNumberId
		    type
	    }
    }
} 
query GetPhoneTypes {
	phoneTypes {
	created
	id
	modified
	order
	type
	}
}
query GetAllLegalEntityPhoneNumbers($input: UUID!) {
	allLegalEntityPhoneNumbers(legalEntityId: $input) {
	countryCode
	created
	extension
	id
	mainNumber
	modified
	}
}

query GetAllCountries {
  allCountries {
    abbreviation
    active
    code
    name
    phoneCode
    phoneMask
    postalCodeMask
  }
}

query GetUserSettings {
  userSettings {
    key
    value
  }
}
