query GetIndemnitorsByAccount($accountNum: String!) {
    indemnitorsByAccount(accountNum: $accountNum){
        accountNum
        agreementDate
        agreementForm
        agreementType
        created
        encryptSpouseTaxId
        executionDate
        familyName
        fullName
        givenName
        id
        indemnityAmount
        mainEmailAddress
        middleInitial
        modified
        netLiquidAssets
        netWorth
        signatory
        spouseIndemnitor
        title
    }
}