query GetAccountPrograms($accountNum: String!){
    accountPrograms(accountNum: $accountNum){
        accountNum
        aggregate
        approvedByName
        approvedDate
        createdByName
        effective
        expiration
        id
        requireExpiration
        single
        status
        statusId
        logs {
            accountNum
            newAggregate
            newSingle
            newStatus
            oldAggregate
            oldSingle
            oldStatus
            statusChangeByFullName
            statusDate
        }
    }
}

query GetAccountProgramById($id: UUID!) {
    accountProgramById(id: $id) {
        id
        createdByName
        accountNum
        single
        aggregate
        effective
        expiration
        status
        approvedByName
        approvedDate
        logs {
            id
            statusDate
            statusChangeByFullName
            oldSingle
            newSingle
            oldAggregate
            newAggregate
            oldStatus
            newStatus
        }
    }
}

query GetLoaLogsByAccount($accountNum: String!) {
    loaLogsByAccount(accountNumber: $accountNum) {
        id
        accountNum
        approvedById
        approvedByName
        bondType
        comments
        conditions
        created
        createdById
        createdByName
        division
        effective
        expiration
        homeOfficeApproved
        loaAggregate
        loaSingle
        sequenceNumber
        status
    }
}