query SearchObligees($input: String!){
  searchObligees (searchString: $input) {
    created
    editedBy
    id
    modified
    notes
    obligeeNum
    printStatusLetter
    type
    idNavigation{
      fullName
    }
  }
}

query GetObligeeById ($input: UUID!){
  obligeeById (id: $input){
    created
    id
    modified
    notes
    obligeeNum
    printStatusLetter
    type
    idNavigation{
      fullName
    }
  }
} 

query GetObligeePrimaryBonds($input: UUID!){
  obligeePrimaryBonds (obligeeId: $input){
    status
    bondNumber
    sfaaclassCode
    bondType{
      bondType
    }
    effective
    expiration
    accountNumNavigation{
      accountNum
      idNavigation{
        fullName
      }
    }
  }
} 

query GetObligeeSecondaryBonds($input: UUID!){
  obligeeSecondaryBonds (obligeeId: $input){
    status
    bondNumber
    sfaaclassCode
    bondType{
      bondType
    }
    effective
    expiration
    accountNumNavigation{
      accountNum
      idNavigation{
        fullName
      }
    }
  }
} 