query GetAllSecurityRoles {
  allSecurityRoles {
    id
    role
    description
    ord
  }
}

query GetSecurityRoleMembers($role: String!) {
  securityRoleMembers(role: $role) {
    id
    name
    isRole
  }
}

query GetAllEmployees {
  allEmployees {
    fullName
    title
    id
  }
}

mutation AddPrincipalToSecurityRole($input: AddPrincipalToSecurityRoleInput!) {
  addPrincipalToSecurityRole(input: $input) {
    boolean
  }
}

mutation RemovePrincipalFromSecurityRole($input:RemovePrincipalFromSecurityRoleInput!){
  removePrincipalFromSecurityRole(input:$input){
    boolean
  }
}

mutation AddSecurityRole($input: AddSecurityRoleInput!) {
  addSecurityRole(input: $input) {
    boolean
  }
} 