query GetAllSecurityRoles {
  allSecurityRoles {
    id
    role
    description
    ord
  }
}

query GetSecurityRoleMembers($role: String!) {
  securityRoleMembers(role: $role) {
    id
    name
    isRole
  }
}

query GetEmployees($activeOnly: Boolean!) {
  employees(activeOnly: $activeOnly) {
    id
    active
    activeDirectoryAccount
    fullName
    title
    primaryBranchId
    initials
    email
    homeOfficeApprover
    underwriterIdNavigation {
      active
      notificationSendTo
      reportsToNavigation {
        id
        fullName
      }
    }
  }
}

query GetSecurityRolesByUser($input: UUID!) {
    securityRolesByUser(principalId: $input) {
        ord
        role
        description
        id
    }
}

query GetActiveDirectoryUsers($usernameSearchText: String!) {
  activeDirectoryUsers(searchText: $usernameSearchText) {
    emails
    fullName
    initials
    username
    title
  }
}

mutation SetEmployeeEmail($input: SetEmployeeEmailInput!) {
  setEmployeeEmail(input:$input){
    boolean
  }
}

mutation CreateEmployee($input:CreateEmployeeInput!) {
  createEmployee(input: $input){
    boolean
  }
}

mutation AddPrincipalToSecurityRole($input: AddPrincipalToSecurityRoleInput!) {
  addPrincipalToSecurityRole(input: $input) {
    boolean
  }
}

mutation RemovePrincipalFromSecurityRole($input:RemovePrincipalFromSecurityRoleInput!){
  removePrincipalFromSecurityRole(input:$input){
    boolean
  }
}

mutation AddSecurityRole($input: AddSecurityRoleInput!) {
  addSecurityRole(input: $input) {
    boolean
  }
} 