<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StrawberryShake.Blazor" Version="15.1.4" />
    <PackageReference Include="StrawberryShake.Transport.WebSockets" Version="15.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\James.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <GenerateGraphQLCodeItems Remove="GraphQL\Mutations\ObligeeMutations.graphql" />
  </ItemGroup>

  <ItemGroup>
    <GraphQL Remove="graphql\mutations\AccountMutations.graphql" />
    <GraphQL Remove="GraphQL\Queries\AccountQueries.graphql" />
    <GraphQL Remove="GraphQL\Queries\BondQueries.graphql" />
    <GraphQL Remove="GraphQL\Queries\General.graphql" />
    <GraphQL Remove="graphql\queries\Imaging.graphql" />
    <GraphQL Remove="GraphQL\Search.graphql" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="GraphQL\Mutations\GeneralMutations.graphql" />
    <None Remove="GraphQL\Mutations\ObligeeMutations.graphql" />
    <None Remove="GraphQL\Queries\AgentQueries.graphql" />
    <None Remove="GraphQL\Queries\Obligee.graphql" />
    <None Remove="GraphQL\Queries\Security.graphql" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="GraphQL\Subscriptions\" />
  </ItemGroup>

  <ItemGroup>
    <GenerateGraphQLCodeItems Remove="GraphQL\Queries\Obligee.graphql" />
  </ItemGroup>

  <ItemGroup>
    <GenerateGraphQLCodeItems Remove="GraphQL\Mutations\GeneralMutations.graphql" />
  </ItemGroup>

  <ItemGroup>
    <GenerateGraphQLCodeItems Remove="GraphQL\Queries\AgentQueries.graphql" />
  </ItemGroup>

</Project>
