<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StrawberryShake.Blazor" Version="13.9.4" />
    <PackageReference Include="StrawberryShake.Transport.WebSockets" Version="13.9.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\James.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <GenerateGraphQLCodeItems Remove="GraphQL\Mutations\ObligeeMutations.graphql" />
  </ItemGroup>

  <ItemGroup>
    <GraphQL Remove="GraphQL\Queries\General.graphql" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="GraphQL\Mutations\ObligeeMutations.graphql" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="GraphQL\Subscriptions\" />
  </ItemGroup>

</Project>
