schema {
  query: Query
  mutation: Mutation
  subscription: Subscription
}

type UserProfile {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  initials: String!
  fullName: String!
  title: String
  primaryBranchId: UUID
  username: String!
  underwriter: Boolean!
  homeOfficeApprover: Boolean!
  accountBranchReviewByNavigations: [Account!]!
  accountHomeOfficeReviewByNavigations: [Account!]!
  accountProgramEmailNotificationGroups: [AccountProgramEmailNotificationGroup!]!
  accountProgramUserAuthorityCreatedByNavigations: [AccountProgramUserAuthority!]!
  accountProgramUserAuthorityModifiedByNavigations: [AccountProgramUserAuthority!]!
  accountProgramUserAuthorityUsers: [AccountProgramUserAuthority!]!
  accountStatusLogs: [AccountStatusLog!]!
  agencyCompetitions: [AgencyCompetition!]!
  agencyInventories: [AgencyInventory!]!
  agencyLineOfAuthorityLogs: [AgencyLineOfAuthorityLog!]!
  bondBlocks: [BondBlock!]!
  bondHolds: [BondHold!]!
  bondRequestCctoNavigations: [BondRequest!]!
  bondRequestCommercialCctoNavigations: [BondRequestCommercial!]!
  bondRequestCommercialHomeOfficeApprovedByNavigations: [BondRequestCommercial!]!
  bondRequestCommercialRecordedByNavigations: [BondRequestCommercial!]!
  bondRequestHomeOfficeApproverNavigations: [BondRequest!]!
  lineOfAuthorityLogApprovedByNavigations: [LineOfAuthorityLog!]!
  lineOfAuthorityLogCreatedByNavigations: [LineOfAuthorityLog!]!
  notebookEntries: [NotebookEntry!]!
  obligees: [Obligee!]!
  surcharges: [Surcharge!]!
  underwriterRecommendations: [UnderwriterRecommendation!]!
  userLineOfAuthorityCreatedByNavigations: [UserLineOfAuthority!]!
  userLineOfAuthorityModifiedByNavigations: [UserLineOfAuthority!]!
  userLineOfAuthorityUsers: [UserLineOfAuthority!]!
  voidedBonds: [VoidedBond!]!
}

type AccountProgramDto {
  id: UUID!
  accountNum: String!
  requireExpiration: Boolean!
  effective: DateTime!
  expiration: DateTime
  single: Int!
  aggregate: Int!
  statusId: UUID!
  status: String!
  createdById: UUID!
  createdBy: String!
  approvedBy: String
  approvedDate: DateTime
  logs: [AccountProgramStatusLogDto!]!
}

type ImagingTabType {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  imagingTabId: UUID!
  imagingTypeId: UUID!
  imagingTab: ImagingTab!
  imagingType: ImagingType!
}

type DeleteAgencyPOAPayload {
  boolean: Boolean
}

type SetLegalEntityEmailPayload {
  legalEntityEmail: LegalEntityEmail
}

type WorkInProgressJob {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  accountNum: String!
  wipdate: LocalDate!
  jobNumber: String!
  description: String!
  bondNumber: String
  contractPrice: Long!
  estimatedCost: Long!
  estimatedGrossProfit: Long!
  percentComplete: Float!
  earnedRevenue: Long!
  costToDate: Long!
  grossProfit: Long!
  grossProfitPercent: Decimal
  progressBillings: Long
  underBillings: Long!
  overBillings: Long!
  revenueRemaining: Long!
  costToComplete: Long!
  totalEstimatedGrossProfit: Long!
  jobStatus: String!
  enteredContractPrice: Long
  enteredEstimatedCost: Long
  enteredCostToDate: Long
  enteredProgressBillings: Long
  otherJobsContractPrice: Long
  otherJobsEstimatedCost: Long
  otherJobsCostToDate: Long
  otherJobsProgressBillings: Long
  accountNumNavigation: Account!
  bondNumberNavigation: Bond
  workInProgressSummary: WorkInProgressSummary!
}

type Insurer {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  active: Boolean!
  defaultRateGroup: String
  currencyCountry: String!
  lenumPeopleSoft: String
  writingCompany: String
  agencyLicenses: [AgencyLicense!]!
  bondHolds: [BondHold!]!
  bondTransactions: [BondTransaction!]!
  bonds: [Bond!]!
  currencyCountryNavigation: CountryDm!
  idNavigation: LegalEntity!
  insurerStates: [InsurerState!]!
  onlineBondSystems: [OnlineBondSystem!]!
  powerOfAttorneys: [PowerOfAttorney!]!
  writingCompanyNavigation: WritingCompanyDm
  fullName: String!
  mainAddress: Address
  addresses: [LegalEntityAddress!]!
  mainPhoneNumber: PhoneNumber
  phoneNumbers: [LegalEntityPhone!]!
  mainEmailAddress: String
  emailAddresses: [LegalEntityEmail!]!
}

type InventoryDocumentDm {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  documentType: String!
  agencyInventories: [AgencyInventory!]!
}

type SetAgencyGeneralInfoPayload {
  boolean: Boolean
}

type AccountOutstandingLiabilityByTypeAndClassDto {
  bondType: String!
  bondClass: String!
  amount: Int!
}

type NotebookEntry {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  notebookId: UUID!
  type: String!
  createdBy: UUID!
  category: String
  note: String!
  completed: Boolean!
  completion: DateTime
  reminderTime: DateTime
  columnName: Boolean!
  createdByNavigation: UserProfile!
  notebook: Notebook!
  typeNavigation: NotebookEntryTypeDm!
}

type KeyValuePairOfStringAndString {
  key: String!
  value: String!
}

type AgencyLicenseBulkUpdatePayload {
  boolean: Boolean
}

input SetAccountGeneralInfoPanelInput {
  accountId: UUID!
  fiscalYearEnd: String
  businessType: String
  industryCode: String
  priorSuretyCompany: String
}

type Subscription {
  onAddressModified(addressId: ID!): SubscriptionResultOfAddress!
  onAddressCollectionModified(legalEntityId: ID!): SubscriptionResultOfGuid!
  onLicenseModified: AgencyLicense!
  onSearchResultReady(searchTerm: String!): SubscriptionResultOfListOfJamesSearchResult!
}

type AccountProgramStatusHistory {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  oldStatus: UUID
  newStatus: UUID!
  oldSingle: Int
  newSingle: Int!
  oldAggregate: Int
  newAggregate: Int!
  statusDate: DateTime!
  statusChangeBy: UUID!
  accountProgramId: UUID!
  accountNum: String!
  accountProgram: AccountProgram!
  newStatusNavigation: AccountProgramStatusDm!
  oldStatusNavigation: AccountProgramStatusDm
}

type CreatePhoneNumberPayload {
  boolean: Boolean
}

type AgencyLicenseBulkDeletePayload {
  boolean: Boolean
}

type InsurerState {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  insurerId: UUID!
  state: String!
  insurer: Insurer!
  stateNavigation: State!
}

type LogExceptionPayload {
  boolean: Boolean
}

input DeleteCreditReportInput {
  id: UUID!
}

input LogInformationInput {
  eventId: Int!
  message: String!
  details: String!
  severity: Severity!
  category: String! = "General"
  data: [KeyValuePairOfStringAndStringInput!]
}

type AgencyLineOfAuthorityAgent {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  agencyLineOfAuthorityId: UUID!
  agentId: UUID!
  agencyLineOfAuthority: AgencyLineOfAuthorityLog!
  agent: Agent!
}

type SetAgencyProfitSharingInfoPayload {
  boolean: Boolean
}

input SetBondBlockInput {
  bondBlockId: UUID!
  insurerId: UUID
  prefix: String!
  firstNumber: Int!
  lastNumber: Int!
  agencyRestricted: Boolean!
  issuedBy: UUID
  comments: String
  agencyId: UUID
  enabled: Boolean!
}

input SetCurrentCreditReportLinkInput {
  accountNum: String!
  imagingDocumentId: UUID
}

type EmailTypeDm {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  type: String!
  legalEntityEmails: [LegalEntityEmail!]!
}

type CashFlowStatement {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  accountNum: String!
  statementDate: LocalDate!
  type: String!
  basis: String
  scaling: String!
  taxBasis: String
  quality: String
  netIncome: Int
  depreciationAmoritization: Int
  accountsReceivable: Int
  accountsReceivableRetention: Int
  b2cee: Int
  allOtherCashFlow: Int
  totalCashFlowsOperations: Int
  netFixedAssetsAcquired: Int
  allOtherInvestments: Int
  totalCashInvestments: Int
  distributions: Int
  lineOfCredit: Int
  termDebt: Int
  stockholderNotes: Int
  allOtherFinancing: Int
  totalCashFinancing: Int
  netChangeInCash: Int
  netFixedAssetsAcquiredDebt: Int
  accountNumNavigation: Account!
  basisNavigation: StatementBasisDm
  qualityNavigation: StatementQualityDm
  scalingNavigation: ScalingDm!
  taxBasisNavigation: TaxBasisDm
  typeNavigation: StatementTypeDm!
}

type SetAccountSystemsPayload {
  boolean: Boolean
}

type TaxBasisDm {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  taxBasis: String!
  accounts: [Account!]!
  cashFlowStatements: [CashFlowStatement!]!
  personalFinancialHeaders: [PersonalFinancialHeader!]!
}

input CreateAccountWatchInput {
  id: UUID!
  accountNum: String!
  watchDate: DateTime!
  watchStatus: String!
  reason: String!
  actionPlan: String!
}

input SetDefaultUserSettingInput {
  key: String!
  value: String
}

input SearchOptionsInput {
  account: Boolean!
  activeOnly: Boolean!
  agency: Boolean!
  agent: Boolean!
  bond: Boolean!
  obligee: Boolean!
  people: Boolean!
  personalFinancials: Boolean!
  virtualFile: Boolean!
}

type CreateLicensePayload {
  boolean: Boolean
}

"The `DateTime` scalar represents an ISO-8601 compliant date time type."
scalar DateTime

type AgencyLocationsDto {
  isTopParent: Boolean!
  agency: Agency!
}

input SetEmployeeIsActiveInput {
  employeeId: UUID!
  isActive: Boolean!
}

type Agency {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  agencyNumber: String!
  branch: String!
  status: String!
  comments: String
  nasbp: Boolean!
  w9: Boolean!
  profitSharing: Boolean!
  profitSharingMinimumPremium: Int
  billingContactId: UUID
  nationalProducerNumber: String
  errorsAndOmmissionsCarrier: String
  errorsAndOmmissionsExpiration: DateTime
  errorsAndOmmissionsCoverage: Int
  need1099: Boolean!
  accounts: [Account!]!
  agencyCompetitions: [AgencyCompetition!]!
  agencyErrorAndOmissions: [AgencyErrorAndOmission!]!
  agencyInventories: [AgencyInventory!]!
  agencyLicenses: [AgencyLicense!]!
  agencyStatusLogs: [AgencyStatusLog!]!
  agentsInAgencies: [AgentsInAgency!]!
  bondTransactions: [BondTransaction!]!
  idNavigation: LegalEntity!
  powerOfAttorneys: [PowerOfAttorney!]!
  statusNavigation: AgencyStatusDm!
  voidedBonds: [VoidedBond!]!
  mainAddress: Address
  billingContact: LegalEntity
  agents: [Agent!]!
  inventories: [AgencyInventory!]!
  errorAndOmissions: [AgencyErrorAndOmission!]!
  competition: [AgencyCompetition!]!
  fullName: String!
  addresses: [LegalEntityAddress!]!
  mainPhoneNumber: PhoneNumber
  phoneNumbers: [LegalEntityPhone!]!
  mainEmailAddress: String
  emailAddresses: [LegalEntityEmail!]!
}

type AccountAlertPackageDto {
  alerts: [AccountAlertDto!]!
  claims: [AccountAlertClaimDto!]!
}

input SetAddressInput {
  addressId: UUID!
  address1: String!
  address2: String
  address3: String
  city: String!
  stateCode: String
  postalCode: String
  identifier: String!
}

type ImagingSearchCriteria {
  contentSearchString: String!
  docClass: String!
  fields: String!
  maxResults: Int!
  searchTimeoutSeconds: Int!
  whereClause: String!
}

type Sic {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  code: String!
  name: String!
  general: String!
  riskLevel: String
  bondHolds: [BondHold!]!
  bonds: [Bond!]!
  sicratios: [Sicratio!]!
}

type SetAccountAdditionalInformationPayload {
  boolean: Boolean
}

type PersonalFinancialHeader {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  accountNum: String!
  statementDate: LocalDate!
  type: String
  basis: String
  taxBasis: String
  quality: String
  scaling: String
  statementFor: String!
  comments: String
  personId: UUID!
  basisNavigation: StatementBasisDm
  person: LegalEntity!
  personalFinancialStatements: [PersonalFinancialStatement!]!
  qualityNavigation: StatementQualityDm
  scalingNavigation: ScalingDm
  taxBasisNavigation: TaxBasisDm
  typeNavigation: PersonalFinancialStatementTypeDm
}

type BondTransactionPurpose {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  bondNumber: String!
  transactionGroup: UUID!
  transactionPurpose: String!
  bondMod: Int!
  groupNumber: Int!
  oldValue: String!
  newValue: String!
  bondNumberNavigation: Bond!
  bondTransaction: BondTransaction!
}

type Employee {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  activeDirectoryAccount: String!
  initials: String!
  fullName: String!
  title: String
  email: String
  primaryBranchId: UUID
  homeOfficeApprover: Boolean!
  active: Boolean!
  entraId: String
  activeDirectoryTitle: String
  agencyStatusLogs: [AgencyStatusLog!]!
  branches: [Branch!]!
  notificationGroupMembers: [NotificationGroupMember!]!
  privateEquities: [PrivateEquity!]!
  underwriterHomeOfficeLeadNavigations: [Underwriter!]!
  underwriterIdNavigation: Underwriter
  underwriterReportsToNavigations: [Underwriter!]!
}

type WritingCompanyDm {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  name: String!
  insurers: [Insurer!]!
}

type Query {
  accountByNumber(accountNumber: String): Account
  firstIndemnity(accountNum: String!): LocalDate
  searchAccounts(searchString: String!): [Account!]!
  lastPrivateEquityByAccount(accountNum: String!): PrivateEquity
  lastIndemnitorByAccount(accountNum: String!): Indemnitor
  accountActiveLinesOfAuthority(accountNumber: String!): InforceAccountLOA!
  accountProgramHistory(accountNumber: String!): [AccountProgram!]!
  accountOnly(accountNumber: String): Account
  additionalRelatedParties(accountNumber: String): [AdditionalRelatedParty!]!
  idAccountNumbers: [Account!]!
  searchAccountsByAccountNumber(accountNumberFragment: String! activeOnly: Boolean!): [Account!]!
  searchAccountsByName(searchString: String! activeOnly: Boolean!): [Account!]!
  allAccountWatches(accountNum: String!): [AccountWatch!]!
  allLineOfAuthorityLogs(accountNum: String!): [LineOfAuthorityLog!]!
  accountAnnualPremiums(accountNum: String! type: String!): AccountAnnualPremiumDto!
  accountBondCollaterals(accountNum: String!): [AccountCollateralDto!]!
  accountOutstandingLiability(accountNum: String!): AccountOutstandingLiabilityDto!
  relatedAccounts(accountNum: String!): AccountBondedPrincipleDto!
  accountAlerts(period: Int! accountNum: String!): AccountAlertPackageDto!
  searchAgencies(stringToSearch: String activeOnly: Boolean!): [AgencySearchDto!]!
  agencyByAgencyNumber(agencyNumber: String!): Agency
  agencyById(agencyId: UUID!): Agency
  agencyAccounts(agencyNumber: String!): [AgencyAccountDto!]!
  agencyAccountBonds(accountNum: String!): [AgencyAccountBondDto!]!
  agencyParent(agencyId: UUID!): Agency!
  agencyInventory(agencyId: UUID!): [AgencyInventory!]!
  agencyStatusLog(agencyNumber: String!): [AgencyStatusLog!]!
  agencyBonds(agencyId: UUID! accountNum: String skip: Int! take: Int!): [AgencyBondDto!]!
  agencyBondsCount(agencyId: UUID!): QueryCount!
  agencyAgentsStandard(agencyId: UUID!): [Agent!]!
  agencyAgents(agencyId: UUID!): [AgencyAgentDto!]!
  agencyAgentLicenses(agencyId: UUID! agentId: UUID!): [AgencyLicense!]!
  allActiveAgencies: [AgencyDto!]!
  agencyLicenses(agencyId: UUID! agents: Boolean!): [AgencyLicense!]!
  agencyStatuses: [AgencyStatusDm!]!
  agencyPOAs(agencyId: UUID! activeOnly: Boolean!): [PowerOfAttorney!]!
  poaDocumentNames: [PowerOfAttorneyDocumentNameDm!]!
  allPoaStatuses: [PowerOfAttorneyStatusDm!]!
  agencyRelatedParties(agencyId: UUID!): [AgencyLocationsDto!]!
  agencyCommissionRates(agencyId: UUID!): [AgencyCommission!]!
  idAgencyNumbers: [Agency!]!
  agentByAgentId(agentId: UUID!): Agent!
  searchAgents(searchString: String!): [Agent!]!
  agentLicenses(agentId: UUID!): [AgencyLicense!]!
  bondRequestNumberType(bondNumber: String!): BondRequestNumberType
  bondNumber(bondRequestNumber: String!): String
  searchBondsByBondNumber(bondNumberFragment: String! activeOnly: Boolean!): [Bond!]!
  bondBlocksByAgency(agencyId: UUID! start: DateTime! end: DateTime! filter: String!): [BondBlock!]!
  bondsByBlock(bondBlockId: UUID!): [Bond!]!
  nextBondBlockInitialNumber(prefix: String!): Int!
  branches: [Branch!]!
  creditReport(accountNumber: String!): [CreditReportHistory!]!
  creditReportAgencies: [CreditReportDm!]!
  divisions: [DivisionDm!]!
  address(addressId: UUID!): Address!
  phoneNumber(phoneId: UUID!): PhoneNumber!
  employeeByUserName(userName: String!): Employee!
  allInventoryDocTypes: [InventoryDocumentDm!]!
  allBranches: [Branch!]!
  allLegalEntityAddresses(legalEntityId: UUID!): [Address!]!
  allLegalEntityPhoneNumbers(legalEntityId: UUID!): [PhoneNumber!]!
  allLegalEntityEmails(legalEntityId: UUID!): [LegalEntityEmail!]!
  phoneTypes: [PhoneTypeDm!]!
  addressTypes: [AddressTypeDm!]!
  emailTypes: [EmailTypeDm!]!
  allCountries: [CountryDm!]!
  allWatchStatuses: [WatchStatusDm!]!
  userSettings: [KeyValuePairOfStringAndString!]!
  allBusinessTypeClassCodes: [BusinessTypeClassCodeDm!]!
  allBusinessTypes: [BusinessTypeDm!]!
  allSicCodes: [Sic!]!
  allIndustryCodes: [IndustryCodeDm!]!
  allContractRates: [ContractRate!]!
  allCommercialRates: [CommercialRate!]!
  allRateGroups: [RateGroupDm!]!
  allRiskTypes: [RiskTypeDm!]!
  allCommercialBondTypes: [CommercialBondTypeDm!]!
  allAccountProgramStatuses: [AccountProgramStatusDm!]!
  searchDocuments(imagingId: String! docCategory: ImagingDocumentCategory! documentType: String): [ImagingDocument!]!
  documentDetails(docCategory: ImagingDocumentCategory! documentId: UUID!): ImagingDocument
  imagingSearchCriteria(imagingId: String! docCategory: ImagingDocumentCategory! useDocCategoryAsCriteria: Boolean! = true): ImagingSearchCriteria!
  allImagingTypes: [ImagingType!]!
  allImagingCategoryTabDivisionType: [VImagingCategoryTabDivisionType!]!
  allInsurers: [Insurer!]!
  loaLogsByAccount(accountNumber: String!): [AccountLOADto!]!
  accountLOAs(accountNum: String!): AccountLOAsDto!
  accountPrograms(accountNum: String!): [AccountProgramDto!]!
  accountProgramById(id: UUID!): AccountProgramDto!
  accountAgencyLOA(accountNum: String!): [AccountAgencyLOADto!]!
  obligeeById(id: UUID!): Obligee
  obligeeByObligeeNumber(obligeeNumber: String!): Obligee
  obligeeTypes: [ObligeeTypeDm!]!
  searchObligees(searchString: String!): [Obligee!]!
  obligeePrimaryBonds(obligeeId: UUID!): [Bond!]!
  obligeeSecondaryBonds(obligeeId: UUID!): [Bond!]!
  search(searchTerm: String! options: SearchOptionsInput!): String!
  allSecurityRoles: [SecurityRole!]!
  securityRolesByUser(principalId: UUID!): [SecurityRole!]!
  securityRoleMembers(role: String!): [SecurityRoleMember!]!
  employees(activeOnly: Boolean!): [Employee!]!
  activeDirectoryUsers(searchText: String!): [PotentialEmployeeActiveDirectoryInfo!]!
  allStates: [State!]!
  underwriters: [Underwriter!]!
  underwriterRecommendationByAccount(accountNumber: String!): [UnderwriterRecommendation!]!
  userSetting(key: String!): UserSetting
  allUserSettings: [KeyValuePairOfStringAndString!]!
  userEmployeeInfo(username: String!): UserInfoDto
  userLOAByDivision(division: String!): [UserLineOfAuthority!]!
}

type AgencyCommission {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  agencyId: UUID!
  bondType: String!
  minimum: Int!
  maximum: Int
  rate: Float!
  effective: DateTime!
  expiration: DateTime
  expireIncluded: Int!
}

type AddPrincipalToSecurityRolePayload {
  boolean: Boolean
}

input CreateAgencyPOAInput {
  poaId: UUID!
  insurerId: UUID!
  agencyId: UUID!
  limit: Int!
  referenceNumber: String
  firstIssued: LocalDate
  currentIssued: LocalDate
  comments: String
  status: String!
}

type UpdateAccountWatchPayload {
  accountWatch: AccountWatch
}

type CreateAgencyStatusLogPayload {
  boolean: Boolean
}

type AgencyLicense {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  agencyId: UUID!
  agentId: UUID
  state: String!
  licenseNumber: String
  isResident: Boolean!
  insurerId: UUID!
  expiration: LocalDate
  comments: String
  appointment: LocalDate
  termination: LocalDate
  appointingState: Boolean!
  isActive: Boolean!
  imagingId: UUID
  agency: Agency!
  agent: Agent
  stateNavigation: State!
  insurer: Insurer!
}

type ObligeeTypeDm {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  type: String!
  obligees: [Obligee!]!
}

type BondHold {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  bondNumber: String!
  accountNum: String!
  bondTypeId: UUID
  risk: String
  branch: String
  underWriterId: UUID
  agencyId: UUID
  agentId: UUID
  obligeeId: UUID
  responsiblePartyId: UUID
  insurerId: UUID
  siccode: String
  state: String
  municipality: String
  effective: DateTime
  expiration: DateTime
  billDate: LocalDate
  sfaacode: Int
  sfaaclassCode: Int
  statusLetterNext: LocalDate
  contractAmount: Int
  bondAmount: Int
  payBondAmout: Int
  premium: Int
  municipalTax: Float
  commissionRate: Float
  riskDescription: Float
  comments: String
  externalRemarks: String
  rate: String
  rateStructure: String
  rateClass: String
  terminationType: String
  cancellable: Boolean!
  renewalProvision: Boolean
  currentTreatyYear: Int
  accountingDate: LocalDate
  bidNumber: String
  homeOfficeApproved: DateTime
  homeOfficeApprovedBy: UUID
  homeOfficeAction: String
  isDirectBill: Boolean
  commissionAmount: Float
  bondPostalCode: String
  daysToCancel: Int
  surchargeApply: Boolean!
  surcharge: Float
  accountNumNavigation: Account!
  agency: LegalEntity
  agent: LegalEntity
  bondType: BondTypeDm
  homeOfficeApprovedByNavigation: UserProfile
  insurer: Insurer
  obligee: LegalEntity
  responsibleParty: LegalEntity
  sfaacodeNavigation: Sfaa
  siccodeNavigation: Sic
  stateNavigation: State
  underWriter: Underwriter
}

enum SearchResultType {
  UNSET
  ACCOUNT
  BOND
  BOND_LIST
  AGENCY
  OBLIGEE
  FILE
  PERSON
}

type SetBondBlockPayload {
  boolean: Boolean
}

input SetAccountAdditionalInformationInput {
  accountId: UUID!
  fullIndemnity: Boolean
  corpIndemnity: Boolean
  personalIndemnity: Boolean
  keyManagementLifeInsurance: Boolean
  managementIncentives: Boolean
  fundedBuySell: Boolean
  multipleActiveOwners: Boolean
  trackCommAccount: Boolean
  berkleyAffiliate: Boolean
  comments: String
}

input SaveCommissionRatesInput {
  rate: AgencyCommissionInput!
}

type BusinessTypeRiskCodeDm {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  businessType: String!
  subType: String
  riskCode: Int!
  isContract: Boolean!
  oldName: String!
  newName: String!
  accounts: [Account!]!
}

type AgencyAccountBondDto {
  bondNumber: String!
  effective: DateTime!
  expiration: DateTime!
  amount: Decimal!
  underwriterId: UUID!
  underwriterFullName: String!
  obligeeId: UUID
  obligeeFullName: String
  bondType: String
  siccode: String
  municipality: String
  bondClass: String!
  status: String!
  appointment: DateTime!
  termination: DateTime!
}

type LineOfAuthorityLog {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  accountNum: String!
  sequenceNumber: Int!
  effective: DateTime!
  expiration: DateTime!
  loasingle: Int!
  loaaggregate: Int!
  comments: String
  status: String
  approvedBy: UUID
  approved: DateTime
  division: String
  bondType: String
  conditions: String
  homeOfficeApproved: Boolean!
  createdBy: UUID
  approvedByNavigation: UserProfile
  createdByNavigation: UserProfile
  divisionNavigation: DivisionDm
  statusNavigation: LineOfAuthorityStatusDm
}

type SubscriptionResultOfAddress {
  identifier: String!
  result: Address!
}

type SurchargeTypeDm {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  type: String!
  surcharges: [Surcharge!]!
}

type Ratio {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  accountNum: String!
  statementDate: LocalDate!
  statementType: String
  statementBasis: String
  statementTaxBasis: String
  statementQuality: String
  workingCapitalStated: Long
  totalAssetsStated: Long
  retainedEarningsStated: Long
  earningsBeforeTaxesStated: Long
  netWorthStated: Long
  totalLiabilitiesStated: Long
  totalEquityStated: Long
  totalRevenueStated: Long
  totalCostOfGoodsSoldStated: Long
  currentAssetsStated: Long
  currentLiabilitiesStated: Long
  netIncomeStated: Long
  inventoryStated: Long
  fixedAssetsStated: Long
  accountsReceivableStated: Long
  accountsPayableStated: Long
  subordinatedNotesStated: Long
  retainageReceivedStated: Long
  retainagePayableStated: Long
  cashPlusEarningsGreaterThanBillingsStated: Long
  billingsGreaterThanCostsPlusEarningsStated: Long
  prepaidExpensesStated: Long
  cashInventoryStated: Long
  otherCurrentAssetsStated: Long
  bankDebtStated: Long
  gaexpensesStated: Long
  operatingProfitStated: Long
  incomeAfterTaxesStated: Long
  cashStated: Long
  notesStated: Long
  qscoreStated: Long
  qprofitStated: Long
  qnetworthStated: Long
  qleverageStated: Decimal
  qworkingCapitalStated: Long
  qcratioStated: Decimal
  workingCapitalAllowed: Long
  totalAssetsAllowed: Long
  retainedEarningsAllowed: Long
  earningsBeforeTaxesAllowed: Long
  netWorthAllowed: Long
  totalLiabilitiesAllowed: Long
  totalEquityAllowed: Long
  totalRevenueAllowed: Long
  totalCostOfGoodsSoldAllowed: Long
  currentAssetsAllowed: Long
  currentLiabilitiesAllowed: Long
  netIncomeAllowed: Long
  inventoryAllowed: Long
  fixedAssetsAllowed: Long
  accountsReceivableAllowed: Long
  accountsPayableAllowed: Long
  subordinatedNotesAllowed: Long
  retainageReceivedAllowed: Long
  retainagePayableAllowed: Long
  cashPlusEarningsGreaterThanBillingsAllowed: Long
  billingsGreaterThanCostsPlusEarningsAllowed: Long
  prepaidExpensesAllowed: Long
  cashInventoryAllowed: Long
  otherCurrentAssetsAllowed: Long
  bankDebtAllowed: Long
  gaexpensesAllowed: Long
  operatingProfitAllowed: Long
  incomeAfterTaxesAllowed: Long
  cashAllowed: Long
  notesAllowed: Long
  qscoreAllowed: Long
  qprofitAllowed: Long
  qnetworthAllowed: Long
  qleverageAllowed: Decimal
  qworkingCapitalAllowed: Long
  qcratioAllowed: Decimal
  scaling: String
  singleLoa: Long
  aggregateLoa: Long
  largestJob: Long
  largestBacklog: Long
  cashFromOperations: Long
  cashFromInvestments: Long
  cashFromFinancing: Long
  comments: String
  netChangeCash: Long
  imagingId: UUID
  accountNumNavigation: Account!
  balanceSheets: [BalanceSheet!]!
}

type CreateAccountWatchPayload {
  accountWatch: AccountWatch
}

type SetAccountProgramPayload {
  boolean: Boolean
}

enum ImagingPropertyDataType {
  STRING
  STRING_LIST
  DATE
  DATE_LIST
  INTEGER
  INTEGER_LIST
  DOUBLE
  DOUBLE_LIST
  CHOICE_LIST_STRING
  CHOICE_LIST_INTEGER
  CHOICE_LIST_STRING_MULTI
  CHOICE_LIST_INTEGER_MULTI
  BOOLEAN
  BOOLEAN_LIST
  UNKOWN
}

type SecurityRole {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  role: String!
  ord: Int!
  description: String
  securities: [Security!]!
}

type DeleteCreditReportPayload {
  boolean: Boolean
}

type PhoneTypeDm {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  type: String!
  order: Int!
  legalEntityPhones: [LegalEntityPhone!]!
}

type DeleteBondBlockPayload {
  boolean: Boolean
}

type AgencyBondDto {
  status: String!
  bondNumber: String!
  accountNum: String!
  accountName: String!
  bondType: String!
  beginDate: DateTime!
  endDate: DateTime!
  underWriterId: UUID!
  underWriterName: String!
  sicCode: String!
  obligeeId: UUID
  obligeeName: String!
  bondClass: String!
  branch: String!
  amount: Int!
}

input SetAccountGeneralInfoInput {
  accountId: UUID!
  yearStarted: String
  currentManagementYear: String
  businessClass: String
  businessType: String
  priorSurety: String
  estAnnualPremium: Int
}

type ReferenceTypeDm {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  type: String!
  description: String
  accountReferences: [AccountReference!]!
}

type CountryDm {
  code: String!
  created: DateTime!
  modified: DateTime!
  name: String!
  abbreviation: String!
  active: Boolean!
  phoneCode: String!
  phoneMask: String!
  postalCodeMask: String!
  addressFinalLineFormat: String
  flagImageBase64: String
  insurers: [Insurer!]!
  states: [State!]!
}

type QueryCount {
  count: Int!
}

input SetPowerOfAttorneyDocumentStatusInput {
  id: UUID!
  requested: DateTime
  received: DateTime
  documentTypeId: UUID!
  comments: String
}

type SubscriptionResultOfListOfJamesSearchResult {
  identifier: String!
  result: [JamesSearchResult!]!
}

type PowerOfAttorney {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  insurerId: UUID!
  agencyId: UUID!
  limit: Int
  referenceNumber: String
  firstIssued: LocalDate
  currentIssued: LocalDate
  comments: String
  imagingId: UUID
  status: String!
  agency: Agency!
  insurer: Insurer!
  powerOfAttorneyDocumentStatuses: [PowerOfAttorneyDocumentStatus!]!
  statusNavigation: PowerOfAttorneyStatusDm!
}

type PowerOfAttorneyDocumentNameDm {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  name: String!
  powerOfAttorneyDocumentStatuses: [PowerOfAttorneyDocumentStatus!]!
}

type SetAgencyLicensePayload {
  agencyLicense: AgencyLicense
}

type RegionDm {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  region: String!
  bondTransactions: [BondTransaction!]!
  branches: [Branch!]!
}

type LineOfAuthorityStatusDm {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  status: String!
  agencyLineOfAuthorityLogs: [AgencyLineOfAuthorityLog!]!
  lineOfAuthorityLogs: [LineOfAuthorityLog!]!
}

type AccountWatch {
  id: UUID!
  created: DateTime!
  modified: DateTime
  watchDate: DateTime!
  watchStatus: String!
  reason: String!
  actionPlan: String!
  accountNum: String!
  accountNumNavigation: Account!
  watchStatusNavigation: WatchStatusDm!
}

type ImagingType {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  type: String!
  description: String!
  imagingTabTypes: [ImagingTabType!]!
}

input CreateAgencyInput {
  parentId: UUID!
  fullName: String!
  branch: String!
  nasbp: Boolean!
  w9: Boolean!
  need1099: Boolean!
  profitSharing: Boolean!
  address1: String!
  address2: String!
  address3: String!
  city: String!
  stateCode: String!
  postalCode: String!
  billingAddress1: String!
  billingAddress2: String!
  billingAddress3: String!
  billingCity: String!
  billingStateCode: String!
  billingPostalCode: String!
}

type PotentialEmployeeActiveDirectoryInfo {
  username: String!
  fullName: String!
  emails: [String!]!
  initials: String!
  title: String!
  selectedEmail: String
}

type BondTypeDm {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  bondType: String!
  bondClass: String!
  description: String
  class: String
  active: Boolean!
  bondHolds: [BondHold!]!
  bonds: [Bond!]!
}

type SubscriptionResultOfGuid {
  identifier: String!
  result: UUID!
}

type AgencyDto {
  id: UUID!
  agencyNumber: String!
  fullName: String!
  fullNameDisplay: String!
  status: String!
}

type StatementQualityDm {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  quality: String!
  cashFlowStatements: [CashFlowStatement!]!
  personalFinancialHeaders: [PersonalFinancialHeader!]!
}

type CoPrincipal {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  bondNumber: String!
  accountNum: String!
  profession: String
  yearsInProfession: Int
  liabilityAmount: Float
  comments: String
  accountNumNavigation: Account!
  bondNumberNavigation: Bond!
}

input DeleteLicenseInput {
  licenseId: UUID!
}

type Notebook {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  sourceTable: String!
  notebookEntries: [NotebookEntry!]!
}

input CreateObligeeInput {
  id: UUID!
  fullName: String!
  obligeeType: String!
  printStatusLetter: Boolean!
  notes: String
  address1: String!
  address2: String
  city: String!
  state: String!
  postalCode: String!
  phoneNumber: String
  email: String
}

input CreatePhoneNumberInput {
  phoneId: UUID!
  countryCode: String
  mainNumber: String!
  extension: String
  legalEntityId: UUID!
  phoneType: String!
}

type InforceAccountLOA {
  accountNum: String!
  contractLOA: LineOfAuthorityLog
  commercialLOA: LineOfAuthorityLog
}

type AgencySearchDto {
  id: UUID!
  agencyNumber: String!
  agencyName: String!
  city: String!
  branch: String!
  status: String!
  parentChild: String!
  idNavigation: LegalEntity!
}

type CreateAgencyLicenseDocumentLinkPayload {
  boolean: Boolean
}

input DeleteUnderwriterRecommendationInput {
  id: UUID!
}

type CommercialRate {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  rateGroup: String!
  commercialBondType: String!
  riskType: String!
  minumumAmount: Int!
  maximumAmount: Int!
  amountPerUnit: Float
  unitSize: Int
  annualMinimum: Int
  commercialBondTypeNavigation: CommercialBondTypeDm!
  rateGroupNavigation: RateGroupDm!
  riskTypeNavigation: RiskTypeDm!
}

type AccountProgramChangeStatusPayload {
  boolean: Boolean
}

type SicratioTypeDm {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  type: String!
  sicratios: [Sicratio!]!
}

input SetLegalEntityEmailInput {
  id: UUID!
  legalEntityId: UUID!
  emailAddress: String!
  type: String!
}

type AccountProgramUserAuthority {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  userId: UUID!
  accountClassId: UUID!
  effective: DateTime!
  expiration: DateTime!
  single: Int!
  aggregate: Int!
  createdBy: UUID!
  modifiedBy: UUID!
  createdByNavigation: UserProfile!
  modifiedByNavigation: UserProfile!
  user: UserProfile!
}

type Underwriter {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  notificationSendTo: String
  active: Boolean!
  reportsTo: UUID
  notificationGroup: String
  homeOfficeLead: UUID
  accounts: [Account!]!
  bondHolds: [BondHold!]!
  bondRequestCommercials: [BondRequestCommercial!]!
  bondRequests: [BondRequest!]!
  bondTransactions: [BondTransaction!]!
  bonds: [Bond!]!
  homeOfficeLeadNavigation: Employee
  idNavigation: Employee!
  notificationGroupNavigation: NotificationGroup
  profitCenters: [ProfitCenter!]!
  reportsToNavigation: Employee
}

type Mutation {
  setCurrentCreditReportLink(input: SetCurrentCreditReportLinkInput!): SetCurrentCreditReportLinkPayload!
  setAccountGeneralInfo(input: SetAccountGeneralInfoInput!): SetAccountGeneralInfoPayload!
  setAccountGeneralInfoPanel(input: SetAccountGeneralInfoPanelInput!): SetAccountGeneralInfoPanelPayload!
  setAccountSystems(input: SetAccountSystemsInput!): SetAccountSystemsPayload!
  setAccountAdditionalInformation(input: SetAccountAdditionalInformationInput!): SetAccountAdditionalInformationPayload!
  createAccountWatch(input: CreateAccountWatchInput!): CreateAccountWatchPayload!
  updateAccountWatch(input: UpdateAccountWatchInput!): UpdateAccountWatchPayload!
  deleteAccountWatch(input: DeleteAccountWatchInput!): DeleteAccountWatchPayload!
  setAccountCommercialInfo(input: SetAccountCommercialInfoInput!): SetAccountCommercialInfoPayload!
  setAccountAgencyAndAgent(input: SetAccountAgencyAndAgentInput!): SetAccountAgencyAndAgentPayload!
  createAgency(input: CreateAgencyInput!): CreateAgencyPayload!
  setAgencyInventory(input: SetAgencyInventoryInput!): SetAgencyInventoryPayload!
  setAgencyLicense(input: SetAgencyLicenseInput!): SetAgencyLicensePayload!
  createLicense(input: CreateLicenseInput!): CreateLicensePayload!
  createAgencyStatusLog(input: CreateAgencyStatusLogInput!): CreateAgencyStatusLogPayload!
  createAgencyPOA(input: CreateAgencyPOAInput!): CreateAgencyPOAPayload!
  createAgencyPOADocumentLink(input: CreateAgencyPOADocumentLinkInput!): CreateAgencyPOADocumentLinkPayload!
  createAgencyLicenseDocumentLink(input: CreateAgencyLicenseDocumentLinkInput!): CreateAgencyLicenseDocumentLinkPayload!
  deleteAgencyPOA(input: DeleteAgencyPOAInput!): DeleteAgencyPOAPayload!
  createAgencyInventory(input: CreateAgencyInventoryInput!): CreateAgencyInventoryPayload!
  deleteLicense(input: DeleteLicenseInput!): DeleteLicensePayload!
  deleteAgencyInventory(input: DeleteAgencyInventoryInput!): DeleteAgencyInventoryPayload!
  setPowerOfAttorney(input: SetPowerOfAttorneyInput!): SetPowerOfAttorneyPayload!
  setPowerOfAttorneyDocumentStatus(input: SetPowerOfAttorneyDocumentStatusInput!): SetPowerOfAttorneyDocumentStatusPayload!
  saveCommissionRates(input: SaveCommissionRatesInput!): SaveCommissionRatesPayload!
  deleteAgencyCommissionRate(input: DeleteAgencyCommissionRateInput!): DeleteAgencyCommissionRatePayload!
  setAgencyGeneralInfo(input: SetAgencyGeneralInfoInput!): SetAgencyGeneralInfoPayload!
  agencyLicenseBulkUpdate(input: AgencyLicenseBulkUpdateInput!): AgencyLicenseBulkUpdatePayload!
  agencyLicenseBulkInsert(input: AgencyLicenseBulkInsertInput!): AgencyLicenseBulkInsertPayload!
  agencyLicenseBulkDelete(input: AgencyLicenseBulkDeleteInput!): AgencyLicenseBulkDeletePayload!
  setAgencyProfitSharingInfo(input: SetAgencyProfitSharingInfoInput!): SetAgencyProfitSharingInfoPayload!
  setCreditReport(input: SetCreditReportInput!): SetCreditReportPayload!
  deleteCreditReport(input: DeleteCreditReportInput!): DeleteCreditReportPayload!
  createAddress(input: CreateAddressInput!): CreateAddressPayload!
  createPhoneNumber(input: CreatePhoneNumberInput!): CreatePhoneNumberPayload!
  deleteAddress(input: DeleteAddressInput!): DeleteAddressPayload!
  setAddress(input: SetAddressInput!): SetAddressPayload!
  deletePhoneNumber(input: DeletePhoneNumberInput!): DeletePhoneNumberPayload!
  setLegalEntityEmail(input: SetLegalEntityEmailInput!): SetLegalEntityEmailPayload!
  deleteLegalEntityEmail(input: DeleteLegalEntityEmailInput!): DeleteLegalEntityEmailPayload!
  setUserSetting(input: SetUserSettingInput!): SetUserSettingPayload!
  setDefaultUserSetting(input: SetDefaultUserSettingInput!): SetDefaultUserSettingPayload!
  resetUserSettings: ResetUserSettingsPayload!
  resetUserSetting(input: ResetUserSettingInput!): ResetUserSettingPayload!
  addPrincipalToSecurityRole(input: AddPrincipalToSecurityRoleInput!): AddPrincipalToSecurityRolePayload!
  removePrincipalFromSecurityRole(input: RemovePrincipalFromSecurityRoleInput!): RemovePrincipalFromSecurityRolePayload!
  addSecurityRole(input: AddSecurityRoleInput!): AddSecurityRolePayload!
  setEmployeeIsActive(input: SetEmployeeIsActiveInput!): SetEmployeeIsActivePayload!
  setEmployeeEmail(input: SetEmployeeEmailInput!): SetEmployeeEmailPayload!
  createEmployee(input: CreateEmployeeInput!): CreateEmployeePayload!
  setBondBlock(input: SetBondBlockInput!): SetBondBlockPayload!
  deleteBondBlock(input: DeleteBondBlockInput!): DeleteBondBlockPayload!
  setAccountProgram(input: SetAccountProgramInput!): SetAccountProgramPayload!
  deleteAccountProgram(input: DeleteAccountProgramInput!): DeleteAccountProgramPayload!
  accountProgramChangeStatus(input: AccountProgramChangeStatusInput!): AccountProgramChangeStatusPayload!
  setUnderwriterRecommendation(input: SetUnderwriterRecommendationInput!): SetUnderwriterRecommendationPayload!
  deleteUnderwriterRecommendation(input: DeleteUnderwriterRecommendationInput!): DeleteUnderwriterRecommendationPayload!
  logInformation(input: LogInformationInput!): LogInformationPayload!
  logException(input: LogExceptionInput!): LogExceptionPayload!
  logUser(input: LogUserInput!): LogUserPayload!
  createObligee(input: CreateObligeeInput!): CreateObligeePayload!
}

type SetDefaultUserSettingPayload {
  boolean: Boolean
}

type AgentSystemDm {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  systemName: String!
  onlineBondSystems: [OnlineBondSystem!]!
}

type DeleteAccountWatchPayload {
  boolean: Boolean
}

type AdditionalObligee {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  obligeeId: UUID!
  printStatusLetter: Boolean!
  interest: String
  bondNumber: String!
  bondNumberNavigation: Bond!
}

type PrivateEquity {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  accountNum: String!
  firmName: String!
  year: String!
  enteredBy: UUID!
  accountNumNavigation: Account!
  enteredByNavigation: Employee!
}

type ResponsibilityDm {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  responsibility: String!
  keyPersonnel: [KeyPersonnel!]!
}

input DeleteAccountProgramInput {
  accountProgramId: UUID!
}

type AccountAlertClaimDto {
  claimId: String!
  bondNumber: String!
  classCode: String!
}

type Address {
  cityZipLine: String! @deprecated(reason: "UseAddressPhoneFormatService instead.")
  id: UUID!
  created: DateTime!
  modified: DateTime!
  address1: String!
  address2: String
  address3: String
  city: String!
  stateCode: String
  postalCode: String
  agencyInventories: [AgencyInventory!]!
  bonds: [Bond!]!
  branches: [Branch!]!
  legalEntityAddress: LegalEntityAddress
  stateCodeNavigation: State
  state: String!
  country: String!
  countryCode: String!
}

type SetUnderwriterRecommendationPayload {
  boolean: Boolean
}

type AccountReference {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  type: String
  idNavigation: LegalEntity!
  typeNavigation: ReferenceTypeDm
}

type DeleteAddressPayload {
  boolean: Boolean
}

type Bond {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  bondNumber: String!
  currentBondMod: Int!
  accountNum: String!
  bondTypeId: UUID
  effective: DateTime!
  expiration: DateTime!
  status: String!
  underWriterId: UUID!
  agentId: UUID
  renewalProvision: String
  cancellable: Boolean
  insurerId: UUID!
  agencyId: UUID!
  state: String!
  riskDescription: String
  comments: String
  terminationType: String
  sfaaclassCode: Int
  siccode: String
  additionalObligees: Boolean!
  currentTreatyYear: Int
  municipality: String
  bondClass: String!
  risk: String
  shortRiskDescription: String
  jointVenture: Boolean!
  obligeeId: UUID
  responsiblePartyId: UUID
  rateGroup: String!
  rateMultiplier: Float
  ceritifiedMailNumber: String
  nonrenewalLetterMailed: DateTime
  hasCollateral: Boolean!
  subjectToRunoff: Boolean!
  federal: Boolean
  homeOfficeApproved: DateTime
  homeOfficeApprovedBy: String
  homeOfficeAction: String
  lineOfAuthorityExpiration: DateTime
  lineOfAuthoritySingle: Int
  lineOfAuthorityAggregate: Int
  lineOfAuthorityException: Boolean
  lineOfAuthorityExceptionDescription: String
  currentBondLiability: Int!
  currentRunoff: Int!
  estimatedBondLiability: Int
  claim: Boolean!
  attorneyInFactId: UUID
  isDirectBill: Boolean
  directBillAddressId: UUID
  bondPostalCode: String
  daysToCancel: Int
  externalRemarks: String
  sfaabondType: String
  enforceNmls: Boolean
  accountNumNavigation: Account!
  additionalObligeesNavigation: [AdditionalObligee!]!
  agent: LegalEntity
  attorneyInFact: LawEntity
  bondRequest: BondRequest
  bondRequestCommercial: BondRequestCommercial
  bondStatusLetters: [BondStatusLetter!]!
  bondTransactionPurposes: [BondTransactionPurpose!]!
  bondTransactions: [BondTransaction!]!
  coPrincipals: [CoPrincipal!]!
  collaterals: [Collateral!]!
  directBillAddress: Address
  emailHistories: [EmailHistory!]!
  insurer: Insurer!
  openClaims: [OpenClaim!]!
  sfaabondTypeNavigation: SfaabondTypeDm
  siccodeNavigation: Sic
  stateNavigation: State!
  underWriter: Underwriter!
  workInProgressJobs: [WorkInProgressJob!]!
  bondType: BondTypeDm!
  type: String!
  agency: LegalEntity!
  obligee: LegalEntity!
  responsibleParty: LegalEntity
}

type BondStatusLetter {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  bondNumber: String!
  sent: LocalDate!
  receivedBack: LocalDate
  percentComplete: Float
  bondNumberNavigation: Bond!
}

input DeletePhoneNumberInput {
  phoneId: UUID!
}

type CreateAgencyPOAPayload {
  boolean: Boolean
}

type BondRequestNumberType {
  bondRequestNumber: String!
  type: String!
}

type LegalEntityAddress {
  legalEntityId: UUID!
  addressId: UUID!
  type: String!
  address: Address!
  legalEntity: LegalEntity!
  typeNavigation: AddressTypeDm!
}

type AgencyErrorAndOmission {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  agencyId: UUID!
  carrier: String!
  expiration: LocalDate!
  coverageLimit: Int!
  agency: Agency!
}

type LegalEntityEmail {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  legalEntityId: UUID!
  type: String!
  emailAddress: String!
  legalEntity: LegalEntity!
  typeNavigation: EmailTypeDm!
}

input SetAccountSystemsInput {
  accountId: UUID!
  estimatingSystem: String
  estimatingSignoff: String
  internalAccountingSystem: String
  interimWips: Boolean
  interimPOCs: Boolean
}

input SetAgencyLicenseInput {
  licenseId: UUID!
  agencyId: UUID!
  agentId: UUID
  appointingState: Boolean!
  comments: String
  appointment: LocalDate
  expiration: LocalDate
  termination: LocalDate
  insurerId: UUID!
  isResident: Boolean!
  licenseNumber: String
  state: String!
  isActive: Boolean!
}

input CreateEmployeeInput {
  username: String!
  fullName: String!
  initials: String!
  title: String!
  email: String!
}

type JamesSearchResult {
  name: String!
  entity: LegalEntity!
  type: SearchResultType!
  fromDescription: Boolean!
  confidence: Int!
  bondList: [Bond!]
  document: ImagingDocument
  parent: LegalEntity
  accountNum: String
  agencyNumber: String
  searchString: String!
}

type LegalEntity {
  _LetterInitialsOfIndividual: String!
  mainAddress: Address
  mainPhoneNumber: PhoneNumber
  mainEmail: String
  id: UUID!
  created: DateTime!
  modified: DateTime!
  parent: UUID!
  fullName: String!
  givenName: String
  familyName: String
  middleInitial: String
  entityType: String!
  website: String
  isIndividual: Boolean!
  taxIdEncrypted: String
  accountCpacontacts: [Account!]!
  accountCpafirms: [Account!]!
  accountIdNavigation: Account
  accountReference: AccountReference
  additionalRelatedParty: AdditionalRelatedParty
  agencyBillingContacts: [Agency!]!
  agencyIdNavigation: Agency
  agent: Agent
  bondAgencies: [Bond!]!
  bondAgents: [Bond!]!
  bondHoldAgencies: [BondHold!]!
  bondHoldAgents: [BondHold!]!
  bondHoldObligees: [BondHold!]!
  bondHoldResponsibleParties: [BondHold!]!
  bondObligees: [Bond!]!
  bondRequestCommercials: [BondRequestCommercial!]!
  bondResponsibleParties: [Bond!]!
  entityTypeNavigation: LegalEntityTypeDm!
  indemnitor: Indemnitor
  insurer: Insurer
  inverseParentNavigation: [LegalEntity!]!
  keyPersonnel: KeyPersonnel
  lawEntity: LawEntity
  legalEntityAddresses: [LegalEntityAddress!]!
  legalEntityEmails: [LegalEntityEmail!]!
  legalEntityPhones: [LegalEntityPhone!]!
  obligee: Obligee
  obligeeContact: ObligeeContact
  onlineBondSystems: [OnlineBondSystem!]!
  parentNavigation: LegalEntity
  personalFinancialHeaders: [PersonalFinancialHeader!]!
}

type SetAddressPayload {
  address: Address
}

type SetAccountGeneralInfoPayload {
  boolean: Boolean
}

type BalanceSheet {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  accountNum: String!
  statementDate: LocalDate!
  accountType: String!
  sequence: Int!
  accountName: String
  stated: Int
  adjustment: Int
  asAllowed: Int
  comments: String
  accountNumNavigation: Account!
  ratio: Ratio!
  subaccounts: [Subaccount!]!
}

type LegalEntityTypeDm {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  entityType: String!
  legalEntities: [LegalEntity!]!
}

type AccountStatusDm {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  accountStatus: String!
  active: Boolean!
  accountStatusLogs: [AccountStatusLog!]!
}

type AccountAlertDto {
  type: String!
  alert: String!
  date: DateTime
  link: String!
  dateText: String!
}

input SetEmployeeEmailInput {
  employeeId: UUID!
  email: String!
}

type EmailHistory {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  from: String!
  fromName: String!
  to: String!
  toName: String!
  cc: String
  accountNum: String!
  bondNumber: String!
  sent: DateTime!
  action: String!
  isContract: Boolean!
  accountNumNavigation: Account!
  actionNavigation: EmailActionDm!
  bondNumberNavigation: Bond!
}

type AgencyInventory {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  agencyId: UUID!
  sent: DateTime
  quantity: Int
  documentType: String!
  addressee: String
  addressId: UUID
  approver: UUID!
  comments: String
  address: Address
  agency: Agency!
  approverNavigation: UserProfile!
  documentTypeNavigation: InventoryDocumentDm!
}

type DefaultGeneralLedgerAccount {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  accountName: String!
  accountClass: String!
  accountType: String!
  fundedDebt: Boolean!
  accountClassNavigation: AccountClassDm!
}

input AddSecurityRoleInput {
  role: String!
  description: String!
  ord: Int!
}

input SetAccountAgencyAndAgentInput {
  accountId: UUID!
  agencyNumber: String!
  agentId: UUID
}

type UserSetting {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  username: String!
  key: String!
  value: String!
}

type ImagingChoice {
  displayValue: String!
  value: String!
}

type BidResultDm {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  description: String!
  order: Int!
  bondRequests: [BondRequest!]!
}

type AccountProgramEmailNotificationGroup {
  id: UUID!
  created: DateTime
  modified: DateTime
  userId: UUID!
  sendTo: String
  user: UserProfile!
}

type AgencyLicenseBulkInsertPayload {
  boolean: Boolean
}

type DeletePhoneNumberPayload {
  boolean: Boolean
}

type ResetUserSettingsPayload {
  boolean: Boolean
}

type NotebookEntryTypeDm {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  type: String!
  notebookEntries: [NotebookEntry!]!
}

type SetEmployeeIsActivePayload {
  boolean: Boolean
}

type LineOfBusinessDm {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  lineOfBusiness: String!
  profitCenters: [ProfitCenter!]!
}

type CreateAddressPayload {
  boolean: Boolean
}

type PersonalFinancialStatementTypeDm {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  type: String!
  personalFinancialHeaders: [PersonalFinancialHeader!]!
}

type AccountAgencyLOADto {
  id: UUID!
  effective: DateTime!
  expiration: DateTime!
  loaSingle: Int!
  loaAggregate: Int!
  division: String
  bondType: String
  created: DateTime!
  sequenceNumber: Int!
  createdById: UUID
  createdByName: String
}

type Indemnitor {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  accountNum: String!
  agreementDate: LocalDate!
  agreementType: String
  agreementForm: String
  netLiquidAssets: Int
  netWorth: Int
  indemnityAmount: Int
  spouseIndemnitor: Boolean!
  encryptSpouseTaxId: String
  signatory: String
  title: String
  executionDate: LocalDate
  accountNumNavigation: Account!
  idNavigation: LegalEntity!
  fullName: String!
  mainAddress: Address
  addresses: [LegalEntityAddress!]!
  mainPhoneNumber: PhoneNumber
  phoneNumbers: [LegalEntityPhone!]!
  mainEmailAddress: String
  emailAddresses: [LegalEntityEmail!]!
  givenName: String
  middleInitial: String
  familyName: String
}

type SetCreditReportPayload {
  boolean: Boolean
}

type CreditReportHistory {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  accountNum: String!
  creditReport: String!
  pulled: DateTime!
  rating: String
  definition: String
  remarks: String
  accountNumNavigation: Account!
}

type UserInfoDto {
  employeeId: UUID!
  username: String!
  fullName: String!
  title: String!
  email: String!
  isUnderwriter: Boolean!
  homeOfficeApprover: Boolean!
}

type Security {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  principalId: UUID!
  role: String!
  roleNavigation: SecurityRole!
}

scalar UUID

type AgencyStatusDm {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  status: String!
  agencies: [Agency!]!
  agencyStatusLogNewStatusNavigations: [AgencyStatusLog!]!
  agencyStatusLogOldStatusNavigations: [AgencyStatusLog!]!
}

type ImagingProperty {
  choiceOption: [ImagingChoice!]
  dataType: ImagingPropertyDataType!
  dataTypeSpecified: Boolean!
  dateListValue: [DateTime]!
  dateValue: DateTime!
  dateValueSpecified: Boolean!
  displayName: String
  description: String!
  listValue: [String!]!
  name: String!
  readOnly: Boolean!
  readOnlySpecified: Boolean!
  required: Boolean!
  requiredSpecified: Boolean!
  requiredFormat: String!
  requiredFormatRegex: String!
  systemGenerated: Boolean!
  systemGeneratedSpecified: Boolean!
  value: String
}

type AccountProgram {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  accountNum: String!
  effective: DateTime!
  expiration: DateTime!
  single: Int!
  aggregate: Int!
  comments: String
  statusId: UUID!
  createdBy: String!
  approvedBy: String
  approvedDate: DateTime
  homeOfficeApproved: Boolean!
  accountNumNavigation: Account!
  accountProgramStatusHistories: [AccountProgramStatusHistory!]!
  status: AccountProgramStatusDm!
}

type AccountProgramStatusLogDto {
  id: UUID!
  accountNum: String!
  newStatusId: UUID!
  newStatus: String!
  oldStatusId: UUID
  oldStatus: String
  oldSingle: Int
  newSingle: Int!
  oldAggregate: Int
  newAggregate: Int!
  statusDate: DateTime!
  statusChangeBy: UUID!
  statusChangeByFullName: String
}

"The `Decimal` scalar type represents a decimal floating-point number."
scalar Decimal

input AgencyLicenseBulkInsertInput {
  licenses: [AgencyLicenseBulkInput!]!
}

type VoidedBond {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  bondNumber: String!
  agencyId: UUID!
  comments: String
  voidedBy: UUID!
  agency: Agency!
  voidedByNavigation: UserProfile!
}

type AccountBondedPrincipleDto {
  parentAccount: RelatedAccountDto!
  relatedAccounts: [RelatedAccountDto!]!
}

type CommercialFinancial {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  accountNum: String!
  period: String!
  cash: Long
  totalAssets: Long
  currentLiabilities: Long
  longTermLiabilities: Long
  longTermDebt: Long
  revenue: Long
  costOfGoodsSold: Long
  interest: Long
  taxes: Long
  netIncome: Long
  depreciation: Long
  amortization: Long
  capitalExpenditures: Long
  netCashFromOperations: Long
  grossProfit: Long
  totalLiabilities: Long
  totalDebt: Long
  scaling: String!
  complete: Boolean!
  shortTermDebt: Long
  scalingNavigation: ScalingDm!
}

"The `LocalDate` scalar type represents a ISO date string, represented as UTF-8 character sequences YYYY-MM-DD. The scalar follows the specification defined in RFC3339"
scalar LocalDate

type SetAgencyInventoryPayload {
  agencyInventory: AgencyInventory
}

input AgencyLicenseBulkInput {
  id: UUID!
  agencyId: UUID!
  agentId: UUID
  state: String!
  licenseNumber: String
  isResident: Boolean!
  insurerId: UUID!
  expiration: LocalDate
  comments: String
  appointment: LocalDate
  termination: LocalDate
  appointingState: Boolean!
  isActive: Boolean!
}

type RiskTypeDm {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  riskType: String!
  commercialRates: [CommercialRate!]!
}

type BondRequest {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  bondRequestNumber: String!
  accountNum: String!
  requested: LocalDate!
  bidDate: LocalDate
  obligeeId: UUID
  estimatedStart: LocalDate
  estimatedFinish: LocalDate
  contractNumber: String
  projectName: String
  description: String
  estimatedContractPrice: Int
  withdrawalPenalty: String
  performanceBondAmount: Int
  paymentBondAmount: Int
  maintenanceTerm: String
  penalties: String
  paymentFrequency: String
  retainage: String
  specialHazards: String
  geographicConcerns: String
  comments: String
  conditions: String
  wipworkOnHand: Long
  wipdate: LocalDate
  newContractsLowBids: Int
  estimatedBacklogRunoff: Int
  totalWorkOnHand: Long
  lineOfCreditSingle: Int
  lineOfCreditAggregate: Int
  lineOfCreditExpiration: LocalDate
  requestedBy: String
  approvedBy: String
  bondNumber: String
  laborPercentage: Int
  materialPercentage: Int
  subcontractedPercentage: Int
  generalConditionsPercentage: Int
  estimateGrossProfitPercentage: Int
  equipmentPercentage: Int
  bidResult: String
  homeOfficeApproved: DateTime
  homeOfficeApprover: UUID
  homeOfficeEmailSent: DateTime
  homeOfficeAction: String
  underWriterId: UUID
  requestType: String!
  outstandingBids: Int
  adjustments: Int
  actualBidAmount: Int
  approvedBidAmount: Int
  ccto: UUID
  status: String!
  homeOfficeConditions: String
  accountNumNavigation: Account!
  bidResultNavigation: BidResultDm
  bidSubcontractors: [BidSubcontractor!]!
  bondNumberNavigation: Bond
  cctoNavigation: UserProfile
  homeOfficeApproverNavigation: UserProfile
  obligee: Obligee
  otherBids: [OtherBid!]!
  statusNavigation: BidStatusDm!
  underWriter: Underwriter
}

type Branch {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  branchKey: String!
  name: String!
  branchOfficeAddressId: UUID!
  phoneId: UUID!
  homeOffice: Boolean!
  emailReceiver: String!
  bccreceiver: String
  generalLedgerCode: String
  active: Boolean!
  region: String!
  headCount: Int
  homeOfficeLead: UUID!
  accounts: [Account!]!
  branchOfficeAddress: Address!
  homeOfficeLeadNavigation: Employee!
  phone: PhoneNumber!
  regionNavigation: RegionDm!
}

input AddPrincipalToSecurityRoleInput {
  principalId: UUID!
  role: String!
}

type AccountClassDm {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  accountClass: String!
  name: String!
  divisionGeneralLedgerCode: Int
  active: Boolean!
  lineOfAuthorityNotificationGroup: String
  bondTransactions: [BondTransaction!]!
  defaultGeneralLedgerAccounts: [DefaultGeneralLedgerAccount!]!
}

input AgencyCommissionInput {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  agencyId: UUID!
  bondType: String!
  minimum: Int!
  maximum: Int
  rate: Float!
  effective: DateTime!
  expiration: DateTime
  expireIncluded: Int!
}

type AdditionalRelatedParty {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  accountNum: String!
  indemnity: Boolean!
  financialStatements: Boolean!
  guarantor: Boolean!
  comments: String
  accountNumNavigation: Account!
  idNavigation: LegalEntity!
}

type ResetUserSettingPayload {
  boolean: Boolean
}

input SetUserSettingInput {
  key: String!
  value: String
}

input SetAgencyProfitSharingInfoInput {
  agencyId: UUID!
  profitSharing: Boolean!
  profitSharingMinimumPremium: Int
}

type DeleteUnderwriterRecommendationPayload {
  boolean: Boolean
}

type AccountLOADto {
  id: UUID!
  created: DateTime!
  createdById: UUID
  createdByName: String
  approvedById: UUID
  approvedByName: String
  accountNum: String!
  sequenceNumber: Int!
  effective: DateTime!
  expiration: DateTime!
  loaSingle: Int!
  loaAggregate: Int!
  division: String
  bondType: String
  homeOfficeApproved: Boolean!
  comments: String
  conditions: String
  status: String
}

enum ImagingDocumentCategory {
  INVALID
  ACCOUNT
  BOND
  AGENCY
  COMM_BID
  CONT_BID
  BILLING
}

type AccountCollateralDto {
  bondNumber: String
  bank: String!
  type: String
  amount: Int!
  expirationDate: LocalDate
}

input UpdateAccountWatchInput {
  id: UUID!
  watchStatus: String!
  reason: String!
  actionPlan: String!
}

type BidStatusDm {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  status: String!
  order: Int!
  bondRequestCommercials: [BondRequestCommercial!]!
  bondRequests: [BondRequest!]!
}

type AgencyCompetition {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  accountNum: String!
  agencyId: UUID!
  annualBusiness: Int!
  annualCommission: Int
  enteredBy: UUID!
  accountNumNavigation: Account!
  agency: Agency!
  enteredByNavigation: UserProfile!
}

type BondTransaction {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  bondNumber: String!
  bondMod: Int!
  groupNumber: Int!
  accountNum: String!
  type: String
  branch: String!
  midtermDescription: String
  paymentBondAmount: Int
  premium: Int!
  bondAmount: Int!
  contractAmount: Int
  effective: DateTime!
  expiration: DateTime!
  coverageDate: DateTime!
  billDate: DateTime!
  commissionRate: Float!
  commissionAmount: Float!
  adminFee: Float
  surcharge: Float!
  municipalTax: Float!
  comments: String
  accountingDate: LocalDate!
  paidToDate: Float!
  agencyId: UUID!
  netDue: Float!
  earned: Float!
  unearned: Float!
  sfaaCode: Int!
  directBill: Boolean!
  region: String!
  accountClass: String!
  surchargeApply: Boolean!
  agencyChange: UUID
  transactionPurpose: String
  transactionGroup: UUID!
  rate: String
  rateStructure: String
  rateClass: String
  underwriterId: UUID!
  state: String
  insurerId: UUID
  accountClassNavigation: AccountClassDm!
  accountNumNavigation: Account!
  agency: Agency!
  bondNumberNavigation: Bond!
  bondTransactionPurposes: [BondTransactionPurpose!]!
  insurer: Insurer
  regionNavigation: RegionDm!
  sfaaCodeNavigation: Sfaa!
  stateNavigation: State
  underwriter: Underwriter!
}

type OtherBid {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  bidNumber: String!
  bidder: String!
  amount: Int!
  bidNumberNavigation: BondRequest!
}

type ImagingTab {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  tabName: String!
  description: String!
  imagingCategoryTabDivisions: [ImagingCategoryTabDivision!]!
  imagingTabTypes: [ImagingTabType!]!
}

input SetAccountProgramInput {
  programId: UUID!
  accountNum: String!
  effective: DateTime!
  expiration: DateTime
  single: Int!
  aggregate: Int!
  comments: String
  statusId: UUID!
}

"Defines when a policy shall be executed."
enum ApplyPolicy {
  "Before the resolver was executed."
  BEFORE_RESOLVER
  "After the resolver was executed."
  AFTER_RESOLVER
  "The policy is applied in the validation step before the execution."
  VALIDATION
}

type PhoneNumber {
  formatted(showCountryCode: Boolean! = false): String!
  id: UUID!
  created: DateTime!
  modified: DateTime!
  countryCode: String!
  mainNumber: String!
  extension: String
  accounts: [Account!]!
  branches: [Branch!]!
  legalEntityPhone: LegalEntityPhone
}

type IndustryCodeDm {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  code: String!
  industry: String!
  accounts: [Account!]!
}

type BondBlock {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  prefix: String!
  firstNumber: Int!
  lastNumber: Int!
  enabled: Boolean!
  agencyRestricted: Boolean!
  issuedBy: UUID
  comments: String
  agencyId: UUID
  issuedByNavigation: UserProfile
}

type AccountAnnualPremiumDto {
  trailingTwelveMonths: Int!
  yearToDate: Int!
}

type AddressTypeDm {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  type: String!
  order: Int!
  legalEntityAddresses: [LegalEntityAddress!]!
}

type SecurityRoleMember {
  id: UUID!
  name: String!
  isRole: Boolean!
}

input CreateAgencyInventoryInput {
  inventoryId: UUID!
  agencyId: UUID!
  dateSent: DateTime!
  quantity: Int!
  documentType: String!
  addressee: String!
  address1: String!
  address2: String
  address3: String
  city: String!
  stateCode: String
  postalCode: String
  approverId: UUID!
}

type Agent {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  nationalProducerNumber: String
  agencyLicenses: [AgencyLicense!]!
  agencyLineOfAuthorityAgents: [AgencyLineOfAuthorityAgent!]!
  agentsInAgencies: [AgentsInAgency!]!
  idNavigation: LegalEntity!
  accounts: [Account!]!
  licenses: [AgencyLicense!]!
  fullName: String!
  mainAddress: Address
  addresses: [LegalEntityAddress!]!
  mainPhoneNumber: PhoneNumber
  phoneNumbers: [LegalEntityPhone!]!
  mainEmailAddress: String
  emailAddresses: [LegalEntityEmail!]!
  givenName: String
  middleInitial: String
  familyName: String
}

type AccountLOADetailDto {
  bondType: String
  effective: DateTime!
  expiration: DateTime!
  single: Int!
  aggregate: Int!
  status: String
}

type SetPowerOfAttorneyPayload {
  powerOfAttorney: PowerOfAttorney
}

type ImagingContent {
  filename: String!
  mimeType: String!
}

type CreateAgencyInventoryPayload {
  boolean: Boolean
}

type OpenClaim {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  bondNumber: String!
  claimNumber: String!
  adjusterName: String!
  reserve: Decimal
  bondNumberNavigation: Bond!
}

input SetPowerOfAttorneyInput {
  poaId: UUID!
  insurerId: UUID!
  limit: Int
  referenceNumber: String
  firstIssued: LocalDate
  currentIssued: LocalDate
  comments: String
  status: String!
}

type NotificationGroup {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  groupName: String!
  description: String
  notificationGroupMembers: [NotificationGroupMember!]!
  underwriters: [Underwriter!]!
}

input DeleteAgencyPOAInput {
  poaId: UUID!
}

type CreateAgencyPayload {
  agency: Agency
}

type PowerOfAttorneyStatusDm {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  status: String!
  powerOfAttorneys: [PowerOfAttorney!]!
}

type CommercialBondTypeDm {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  commercialBondType: String!
  commercialRates: [CommercialRate!]!
}

type WatchStatusDm {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  watchStatus: String!
  accountWatches: [AccountWatch!]!
}

type ImagingDocument {
  guid: String!
  documentClass: String!
  folderPath: String
  entryDate: DateTime!
  properties: [ImagingProperty!]
  contentList: [ImagingContent!]
  description: String!
  filename: String!
  documentType: String
}

type SetAccountAgencyAndAgentPayload {
  boolean: Boolean
}

type DeleteLegalEntityEmailPayload {
  boolean: Boolean
}

type SetCurrentCreditReportLinkPayload {
  boolean: Boolean
}

type LogInformationPayload {
  boolean: Boolean
}

type SetUserSettingPayload {
  boolean: Boolean
}

type SfaabondTypeDm {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  sfaabondType: String!
  bonds: [Bond!]!
}

type CommercialRegionDm {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  region: String!
  profitCenters: [ProfitCenter!]!
}

type OnlineBondSystem {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  legalEntityId: UUID!
  systemName: String!
  insurerId: UUID!
  writingLimit: Int
  insurer: Insurer!
  legalEntity: LegalEntity!
  systemNameNavigation: AgentSystemDm!
}

type StatementTypeDm {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  type: String!
  cashFlowStatements: [CashFlowStatement!]!
}

type Obligee {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  obligeeNum: String!
  type: String
  editedBy: UUID
  printStatusLetter: Boolean!
  notes: String
  bondRequests: [BondRequest!]!
  editedByNavigation: UserProfile
  idNavigation: LegalEntity!
  typeNavigation: ObligeeTypeDm
  fullName: String!
  mainAddress: Address
  addresses: [LegalEntityAddress!]!
  mainPhoneNumber: PhoneNumber
  phoneNumbers: [LegalEntityPhone!]!
  mainEmailAddress: String
  emailAddresses: [LegalEntityEmail!]!
  givenName: String
  middleInitial: String
  familyName: String
}

type UserLineOfAuthority {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  userId: UUID!
  single: Int!
  aggregate: Int!
  expiration: LocalDate!
  divisionCode: String!
  bondType: String!
  createdBy: UUID!
  modifiedBy: UUID!
  createdByNavigation: UserProfile!
  modifiedByNavigation: UserProfile!
  user: UserProfile!
}

type DeleteLicensePayload {
  boolean: Boolean
}

"The `Long` scalar type represents non-fractional signed whole 64-bit numeric values. Long can represent values between -(2^63) and 2^63 - 1."
scalar Long

type NotificationGroupMember {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  groupName: String!
  employeeId: UUID!
  employee: Employee!
  groupNameNavigation: NotificationGroup!
}

type RelatedAccountDto {
  accountNum: String!
  accountName: String!
  accountStatus: String!
}

type PersonalFinancialSubaccount {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  parentAccountId: UUID!
  sequence: Int!
  stated: Int
  adjustment: Int
  asAllowed: Int
  comments: String
  parentAccount: PersonalFinancialStatement!
}

type Sfaa {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  code: Int!
  description: String
  general: String!
  rateClass: String
  riskType: String
  nmlsclassCode: Boolean!
  bondHolds: [BondHold!]!
  bondRequestCommercials: [BondRequestCommercial!]!
  bondTransactions: [BondTransaction!]!
}

input DeleteLegalEntityEmailInput {
  id: UUID!
}

type SaveCommissionRatesPayload {
  boolean: Boolean
}

type LegalEntityPhone {
  legalEntityId: UUID!
  phoneNumberId: UUID!
  type: String!
  legalEntity: LegalEntity!
  phoneNumber: PhoneNumber!
  typeNavigation: PhoneTypeDm!
}

type BusinessTypeDm {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  businessType: String!
  accounts: [Account!]!
}

type Surcharge {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  state: String!
  amount: Float!
  effective: LocalDate!
  expiration: LocalDate!
  exclude: Boolean!
  type: String!
  createdBy: UUID!
  createdByNavigation: UserProfile!
  stateNavigation: State!
  typeNavigation: SurchargeTypeDm!
}

type Account {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  accountNum: String!
  openClaim: Boolean!
  yearOpened: String
  branch: String!
  agencyNumber: String
  dunBradstreetRate: String
  dunBradstreetDate: LocalDate
  dunBradstreetSic: String
  bank: String
  bankReferenceName: String
  bankAverageBalance: Int
  bankPhoneId: UUID
  bankLastContacted: LocalDate
  bankLoc: Int
  bankLocexpires: LocalDate
  bankLocused: Int
  bankLochigh: Int
  bankLochighDate: LocalDate
  bankLocsecurity: String
  publicPercent: Float
  privatePercent: Float
  subcontractPercent: Float
  subcontractProtection: String
  geographicSpread: String
  paydexIntelliscore: Int
  priorSuretyCompany: String
  currentManagementYear: String
  indemnityFull: Boolean!
  indemnityCorp: Boolean!
  indemnityPerson: Boolean!
  berkleyAffiliate: Boolean!
  continuityKeyManagementLifeInsurance: Boolean!
  continuityManagementIncentives: Boolean!
  continuityFundedBuySell: Boolean!
  continuityActiveMultipleOwners: Boolean!
  fiscalYearEnd: String
  taxBasis: String
  agentId: UUID
  businessType: String
  division: String!
  rateModifier: Float!
  lawFirmId: UUID
  attorneyId: UUID
  cpafirmId: UUID
  cpacontactId: UUID
  underwriterId: UUID
  naics: String
  homeOfficeReviewBy: UUID
  homeOfficeReviewed: DateTime
  branchReviewBy: UUID
  branchReviewed: DateTime
  homeOfficeLock: Boolean!
  businessTypeClass: String
  fundsControl: Boolean!
  pollutionLiabilityCarrier: String
  pollutionLiabilityExpires: LocalDate
  affiliateCompany: Boolean!
  creditReport: String
  estimatingSystem: String
  estimatingSignoff: String
  accountingSystem: String
  pocinterims: Boolean!
  interimWips: Boolean!
  indemnityComments: String
  creditReportImagingId: UUID
  businessTypeRiskCodeId: UUID
  sicCode: String
  industryCode: String
  sharedSurety: String
  accountPrograms: [AccountProgram!]!
  accountStatusLogs: [AccountStatusLog!]!
  accountWatches: [AccountWatch!]!
  additionalRelatedParties: [AdditionalRelatedParty!]!
  agencyCompetitions: [AgencyCompetition!]!
  agencyNumberNavigation: Agency
  agent: Agent
  attorney: LawEntity
  balanceSheets: [BalanceSheet!]!
  bankPhone: PhoneNumber
  bondHolds: [BondHold!]!
  bondRequestCommercials: [BondRequestCommercial!]!
  bondRequests: [BondRequest!]!
  bondTransactions: [BondTransaction!]!
  bonds: [Bond!]!
  branchNavigation: Branch!
  branchReviewByNavigation: UserProfile
  businessTypeClassNavigation: BusinessTypeClassCodeDm
  businessTypeNavigation: BusinessTypeDm
  businessTypeRiskCode: BusinessTypeRiskCodeDm
  cashFlowStatements: [CashFlowStatement!]!
  coPrincipals: [CoPrincipal!]!
  cpacontact: LegalEntity
  cpafirm: LegalEntity
  creditReportHistories: [CreditReportHistory!]!
  divisionNavigation: DivisionDm!
  emailHistories: [EmailHistory!]!
  homeOfficeReviewByNavigation: UserProfile
  idNavigation: LegalEntity!
  indemnitors: [Indemnitor!]!
  industryCodeNavigation: IndustryCodeDm
  keyPersonnel: [KeyPersonnel!]!
  lawFirm: LawEntity
  personalFinancialStatements: [PersonalFinancialStatement!]!
  privateEquities: [PrivateEquity!]!
  ratios: [Ratio!]!
  taxBasisNavigation: TaxBasisDm
  underwriter: Underwriter
  underwriterRecommendations: [UnderwriterRecommendation!]!
  workInProgressJobs: [WorkInProgressJob!]!
  mainAddress: Address
  agency: Agency
  fullName: String!
  addresses: [LegalEntityAddress!]!
  mainPhoneNumber: PhoneNumber
  phoneNumbers: [LegalEntityPhone!]!
  mainEmailAddress: String
  emailAddresses: [LegalEntityEmail!]!
}

type ContractRate {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  rateGroup: String!
  class: String!
  rateType: String!
  minumumAmount: Int!
  maximumAmount: Int!
  premiumRate: Float
  rateGroupNavigation: RateGroupDm!
}

type DivisionDm {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  divisionCode: String!
  division: String!
  loanotificationGroup: String!
  active: Boolean!
  accounts: [Account!]!
  imagingCategoryTabDivisions: [ImagingCategoryTabDivision!]!
  lineOfAuthorityLogs: [LineOfAuthorityLog!]!
  profitCenters: [ProfitCenter!]!
}

type SetAccountCommercialInfoPayload {
  boolean: Boolean
}

type LogUserPayload {
  string: String
}

type PersonalFinancialStatement {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  accountNum: String!
  statementDate: LocalDate!
  accountType: String!
  sequence: Int!
  accountName: String
  stated: Int
  adjustment: Int
  asAllowed: Int
  comments: String
  headerId: UUID!
  accountNumNavigation: Account!
  header: PersonalFinancialHeader!
  personalFinancialSubaccounts: [PersonalFinancialSubaccount!]!
}

type AgencyAccountDto {
  accountNum: String!
  name: String!
  branch: String!
  branchFullName: String!
  mainAddress: Address
  bonds: [AgencyAccountBondDto!]!
  status: String!
}

input SetAgencyInventoryInput {
  inventoryId: UUID!
  sent: DateTime
  quantity: Int
  documentType: String!
  addressee: String
  addressId: UUID!
  address1: String!
  address2: String
  address3: String
  city: String!
  stateCode: String
  postalCode: String
}

input AgencyLicenseBulkUpdateInput {
  licenses: [AgencyLicenseBulkInput!]!
}

input CreateAgencyPOADocumentLinkInput {
  poaId: UUID!
  imagingDocumentId: UUID
}

input SetCreditReportInput {
  id: UUID!
  creditReportAgency: String!
  accountNum: String!
  pulledDate: DateTime!
  rating: String!
  definition: String!
  remarks: String!
}

type KeyPersonnel {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  accountNum: String!
  encryptYearOfBirth: String
  position: String
  responsibility: String
  yearJoinedCompany: String
  yearEnteredField: String
  spouseName: String
  personalIndemnification: Boolean!
  comments: String
  profession: String
  active: Boolean!
  accountNumNavigation: Account!
  idNavigation: LegalEntity!
  responsibilityNavigation: ResponsibilityDm
  fullName: String!
  mainAddress: Address
  addresses: [LegalEntityAddress!]!
  mainPhoneNumber: PhoneNumber
  phoneNumbers: [LegalEntityPhone!]!
  mainEmailAddress: String
  emailAddresses: [LegalEntityEmail!]!
  givenName: String
  middleInitial: String
  familyName: String
}

type CreateEmployeePayload {
  boolean: Boolean
}

type AccountLOAsDto {
  accountLOAs: [AccountLOADetailDto!]!
  agencyLOAs: [AccountLOADetailDto!]!
  loaTotal: Int!
}

type ImagingCategory {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  category: String!
  imagingCategoryTabDivisions: [ImagingCategoryTabDivision!]!
}

input SetAccountCommercialInfoInput {
  accountId: UUID!
  fullName: String!
  underwriterId: UUID!
  branchKey: String!
  divisionCode: String!
  hoLead: UUID!
  sicCodeId: UUID!
}

input CreateAgencyLicenseDocumentLinkInput {
  licenseId: UUID!
  imagingDocumentId: UUID
}

type DeleteAgencyCommissionRatePayload {
  boolean: Boolean
}

input CreateLicenseInput {
  licenseId: UUID!
  agencyId: UUID!
  agentId: UUID
  appointingState: Boolean!
  comments: String
  appointment: LocalDate
  expiration: LocalDate
  termination: LocalDate
  insurerId: UUID!
  isResident: Boolean!
  licenseNumber: String
  state: String!
  isActive: Boolean!
}

type DeleteAccountProgramPayload {
  boolean: Boolean
}

type BidSubcontractor {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  bidNumber: String!
  name: String!
  trade: String
  amount: Int
  bonded: Boolean!
  bidNumberNavigation: BondRequest!
}

input DeleteAccountWatchInput {
  id: UUID!
}

type AddSecurityRolePayload {
  boolean: Boolean
}

input SetAgencyGeneralInfoInput {
  agencyId: UUID!
  agencyName: String!
  parentId: UUID!
  taxId: String
  npn: String
  w9: Boolean!
  need1099: Boolean!
  nasbp: Boolean!
  branchKey: String!
}

type VImagingCategoryTabDivisionType {
  tabName: String!
  tabDescription: String!
  type: String!
  typeDescription: String!
  category: String!
  divisionCode: String
}

input AgencyLicenseBulkDeleteInput {
  licenseIds: [UUID!]!
}

type CreateObligeePayload {
  obligee: Obligee
}

input DeleteBondBlockInput {
  bondBlockId: UUID!
}

type AgentsInAgency {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  agentId: UUID!
  agencyId: UUID!
  attorneyInFact: Boolean!
  portalUser: Boolean!
  active: Boolean!
  comments: String
  agency: Agency!
  agent: Agent!
}

type Collateral {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  accountNum: String!
  type: String
  amount: Int
  expiration: LocalDate
  autoRenew: Boolean!
  description: String
  bondNumber: String
  bondSpecific: Boolean
  released: DateTime
  bondNumberNavigation: Bond
}

input SetUnderwriterRecommendationInput {
  id: UUID!
  accountNum: String!
  postedBy: UUID!
  comments: String!
  description: String!
}

type SetAccountGeneralInfoPanelPayload {
  boolean: Boolean
}

type Sicratio {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  code: String!
  type: String!
  name: String!
  upperQuartileStated: Float!
  medianStated: Float!
  lowerQuartileStated: Float
  upperQuartileAllowed: Float!
  medianAllowed: Float!
  lowerQuartileAllowed: Float
  sampleSize: Int!
  codeNavigation: Sic!
  typeNavigation: SicratioTypeDm!
}

type PowerOfAttorneyDocumentStatus {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  poaid: UUID!
  requested: LocalDate
  received: LocalDate
  documentTypeId: UUID!
  comments: String
  documentType: PowerOfAttorneyDocumentNameDm!
  poa: PowerOfAttorney!
}

type CreditReportDm {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  creditReport: String!
}

type LawEntity {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  martindaleHubbellRating: String
  comment: String
  accountAttorneys: [Account!]!
  accountLawFirms: [Account!]!
  bonds: [Bond!]!
  idNavigation: LegalEntity!
  fullName: String!
  mainAddress: Address
  addresses: [LegalEntityAddress!]!
  mainPhoneNumber: PhoneNumber
  phoneNumbers: [LegalEntityPhone!]!
  mainEmailAddress: String
  emailAddresses: [LegalEntityEmail!]!
  givenName: String
  middleInitial: String
  familyName: String
}

type RateGroupDm {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  rateGroup: String!
  description: String!
  createdBy: UUID
  commercialRates: [CommercialRate!]!
  contractRates: [ContractRate!]!
}

type AccountProgramStatusDm {
  id: UUID!
  created: DateTime
  modified: DateTime
  description: String!
  oldId: Int
  accountProgramStatusHistoryNewStatusNavigations: [AccountProgramStatusHistory!]!
  accountProgramStatusHistoryOldStatusNavigations: [AccountProgramStatusHistory!]!
  accountPrograms: [AccountProgram!]!
}

input ResetUserSettingInput {
  key: String!
}

type CreateAgencyPOADocumentLinkPayload {
  boolean: Boolean
}

type BondRequestCommercial {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  bondRequestNumber: String!
  accountNum: String!
  requested: LocalDate!
  legacyBidNumber: Int
  status: String!
  estimatedStart: LocalDate
  estimatedFinish: LocalDate
  obligeeId: UUID
  amount: Int
  recordedBy: UUID
  recorded: LocalDate
  recordedMessageSent: DateTime
  homeOfficeAction: String
  homeOfficeActionDate: DateTime
  homeOfficeApprovedBy: UUID
  homeOfficeConditions: String
  bondNumber: String
  description: String
  underWriterId: UUID
  sfaaCode: Int
  ccto: UUID
  lineOfCreditSingle: Int
  lineOfCreditAggregate: Int
  lineOfCreditExpiration: LocalDate
  exposure: Int
  adjustments: Int
  totalExposure: Int
  approvedBidAmount: Int
  accountNumNavigation: Account!
  bondNumberNavigation: Bond
  cctoNavigation: UserProfile
  homeOfficeApprovedByNavigation: UserProfile
  obligee: LegalEntity
  recordedByNavigation: UserProfile
  sfaaCodeNavigation: Sfaa
  statusNavigation: BidStatusDm!
  underWriter: Underwriter
}

type BusinessTypeClassCodeDm {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  businessType: String!
  classCode: Int!
  isContract: Boolean!
  accounts: [Account!]!
}

type DeleteAgencyInventoryPayload {
  boolean: Boolean
}

input LogUserInput {
  message: String! = ""
}

input DeleteAddressInput {
  addressId: UUID!
  identifier: String!
}

type ImagingCategoryTabDivision {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  category: String!
  imagingTabId: UUID!
  divisionCode: String
  categoryNavigation: ImagingCategory!
  divisionCodeNavigation: DivisionDm
  imagingTab: ImagingTab!
}

type ScalingDm {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  scaling: String!
  cashFlowStatements: [CashFlowStatement!]!
  commercialFinancials: [CommercialFinancial!]!
  personalFinancialHeaders: [PersonalFinancialHeader!]!
}

type Subaccount {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  parentAccountId: UUID!
  sequence: Int!
  stated: Int
  adjustment: Int
  asAllowed: Int
  comments: String
  parentAccount: BalanceSheet!
}

type ProfitCenter {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  profitCenter1: String!
  divisionCode: String!
  lineOfBusiness: String!
  location: String!
  locationOverview: String!
  budgetDefault: UUID
  underWriterId: UUID
  effective: LocalDate!
  expiration: LocalDate!
  commercialRegion: String
  budgetDefaultNavigation: ProfitCenter
  commercialRegionNavigation: CommercialRegionDm
  divisionCodeNavigation: DivisionDm!
  inverseBudgetDefaultNavigation: [ProfitCenter!]!
  lineOfBusinessNavigation: LineOfBusinessDm!
  underWriter: Underwriter
}

type SetPowerOfAttorneyDocumentStatusPayload {
  powerOfAttorneyDocumentStatus: PowerOfAttorneyDocumentStatus
}

type AccountOutstandingLiabilityDto {
  outstandingCommercialLiability: Int!
  outstandingContractLiability: Int!
  largestBondEver: Int!
  largestOutstandingBonds: [AccountOutstandingLiabilityByTypeAndClassDto!]!
}

input LogExceptionInput {
  eventId: Int!
  message: String!
  exception: String!
  severity: Severity!
  category: String! = "General"
  data: [KeyValuePairOfStringAndStringInput!]
}

input CreateAddressInput {
  addressId: UUID!
  address1: String!
  address2: String
  address3: String
  city: String!
  stateCode: String
  postalCode: String
  legalEntityId: UUID!
  addressType: String!
  identifier: String!
}

type State {
  code: String!
  created: DateTime!
  modified: DateTime!
  name: String!
  saacode: String
  wrbstateCode: String
  countryCode: String
  addresses: [Address!]!
  agencyLicenses: [AgencyLicense!]!
  bondHolds: [BondHold!]!
  bondTransactions: [BondTransaction!]!
  bonds: [Bond!]!
  countryCodeNavigation: CountryDm
  insurerStates: [InsurerState!]!
  surcharges: [Surcharge!]!
}

type SetEmployeeEmailPayload {
  boolean: Boolean
}

input AccountProgramChangeStatusInput {
  accountProgramId: UUID!
  newStatusTxt: String!
}

input CreateAgencyStatusLogInput {
  id: UUID!
  agencyNumber: String!
  effective: DateTime!
  oldStatus: String!
  newStatus: String!
  changedBy: UUID!
  comments: String
}

type AgencyStatusLog {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  agencyNumber: String!
  effective: DateTime!
  oldStatus: String
  newStatus: String
  changedBy: UUID
  comments: String
  agencyNumberNavigation: Agency!
  changedByNavigation: Employee
  newStatusNavigation: AgencyStatusDm
  oldStatusNavigation: AgencyStatusDm
}

type WorkInProgressSummary {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  accountNum: String!
  wipdate: LocalDate!
  contractPrice: Long!
  estimatedCost: Long!
  estimatedGrossProfit: Long!
  percentComplete: Float!
  earnedRevenue: Long!
  costToDate: Long!
  grossProfit: Long!
  grossProfitPercent: Decimal
  progressBillings: Long
  underBillings: Long!
  overBillings: Long!
  revenueRemaining: Long!
  costToComplete: Long!
  totalEstimatedGrossProfit: Long!
  imagingId: UUID
  workInProgressJobs: [WorkInProgressJob!]!
}

type AgencyLineOfAuthorityLog {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  agencyNumber: String!
  accountNum: String!
  sequenceNumber: Int!
  effective: DateTime!
  expiration: DateTime!
  loasingle: Int!
  loaaggregate: Int!
  comments: String
  status: String
  division: String
  bondType: String
  createdBy: UUID
  conditions: String
  agencyLineOfAuthorityAgents: [AgencyLineOfAuthorityAgent!]!
  createdByNavigation: UserProfile
  statusNavigation: LineOfAuthorityStatusDm
}

type AgencyAgentDto {
  id: UUID!
  agencyId: UUID!
  agentId: UUID!
  fullName: String!
  givenName: String
  middleInitial: String
  familyName: String
  nationalProducerNumber: String!
  email: String!
  phoneNumber: String!
  extension: String!
  aif: Boolean!
}

input DeleteAgencyInventoryInput {
  inventoryId: UUID!
}

type EmailActionDm {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  action: String!
  emailHistories: [EmailHistory!]!
}

input DeleteAgencyCommissionRateInput {
  commRateId: UUID!
}

input RemovePrincipalFromSecurityRoleInput {
  principalId: UUID!
  role: String!
}

type UnderwriterRecommendation {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  accountNum: String!
  postedBy: UUID!
  comments: String
  description: String
  accountNumNavigation: Account!
  postedByNavigation: UserProfile!
}

enum Severity {
  UNSET
  VERBOSE
  DEBUG
  INFORMATION
  WARNING
  ERROR
  FATAL
}

type StatementBasisDm {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  basis: String!
  cashFlowStatements: [CashFlowStatement!]!
  personalFinancialHeaders: [PersonalFinancialHeader!]!
}

type ObligeeContact {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  title: String!
  idNavigation: LegalEntity!
}

type RemovePrincipalFromSecurityRolePayload {
  boolean: Boolean
}

type AccountStatusLog {
  id: UUID!
  created: DateTime!
  modified: DateTime!
  accountNum: String!
  accountStatus: String!
  modifiedBy: UUID!
  comments: String
  effective: DateTime!
  accountNumNavigation: Account!
  accountStatusNavigation: AccountStatusDm!
  modifiedByNavigation: UserProfile!
}

input KeyValuePairOfStringAndStringInput {
  key: String!
  value: String!
}

"The purpose of the `cost` directive is to define a `weight` for GraphQL types, fields, and arguments. Static analysis can use these weights when calculating the overall cost of a query or response."
directive @cost("The `weight` argument defines what value to add to the overall cost for every appearance, or possible appearance, of a type, field, argument, etc." weight: String!) on SCALAR | OBJECT | FIELD_DEFINITION | ARGUMENT_DEFINITION | ENUM | INPUT_FIELD_DEFINITION