<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
	<StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
  </PropertyGroup>

  <ItemGroup>
    <GraphQL Remove="GraphQL\GetAccountByAccountNumber.graphql" />
    <GraphQL Remove="GraphQL\GetAccountByAccountNumberLight.graphql" />
    <GraphQL Remove="GraphQL\GetAgencyAgents.graphql" />
    <GraphQL Remove="GraphQL\GetAgencyBonds.graphql" />
    <GraphQL Remove="GraphQL\GetAgencyLicenses.graphql" />
    <GraphQL Remove="GraphQL\GetStates.graphql" />
    <GraphQL Remove="GraphQL\Mutations\SetAddress.graphql" />
    <GraphQL Remove="GraphQL\Mutations\SetLicense.graphql" />
    <GraphQL Remove="GraphQL\Queries\GetInsurers.graphql" />
    <GraphQL Remove="GraphQL\SearchAgencies.graphql" />
    <GraphQL Remove="GraphQL\Subscriptions\AddressSubs.graphql" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="GraphQL\ApplicationLogging.graphql" />
    <None Remove="GraphQL\GetAccountByAccountNumberLight.graphql" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="8.0.3" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0" />
    <PackageReference Include="Radzen.Blazor" Version="4.25.9" />
    <PackageReference Include="StrawberryShake.Blazor" Version="13.9.0" />
    <PackageReference Include="StrawberryShake.Transport.WebSockets" Version="13.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\James.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <GenerateGraphQLCodeItems Remove="GraphQL\ApplicationLogging.graphql" />
  </ItemGroup>

</Project>
