<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
	<StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="GraphQL\**" />
    <Content Remove="GraphQL\**" />
    <EmbeddedResource Remove="GraphQL\**" />
    <GraphQL Remove="GraphQL\**" />
    <None Remove="GraphQL\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.7" />
    <PackageReference Include="Blazorise.Animate" Version="1.6.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="8.0.7" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0" />
    <PackageReference Include="Radzen.Blazor" Version="4.32.1" />
    <PackageReference Include="StrawberryShake.Blazor" Version="13.9.9" />
    <PackageReference Include="StrawberryShake.Transport.WebSockets" Version="13.9.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Data\JamesDAL.Client\James.Data.Client.csproj" />
    <ProjectReference Include="..\..\Shared\James.Shared.csproj" />
  </ItemGroup>

</Project>
