using James.Data.Imaging;
using James.Shared;
using James.Shared.Imaging;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Runtime.Versioning;
using System.Text.Json;

namespace JamesWebUI.Server.Controllers
{
    /// <summary>
    /// This controller is for uploading and downloading imaging documents
    /// </summary>
    /// <remarks>All other imaging functions should be in an IImagingAccess object</remarks>
    /// <param name="imagingAccess">Exposes imaging functions to the application</param>
    /// <param name="loggingService">Exposes logging functions to the application</param>
    [SupportedOSPlatform("windows")]
    [ApiController]
    [Route("[controller]")]
    [Authorize]
    public class ImagingRepositoryController(ServerImagingAccess imagingAccess, ILoggingService loggingService)
    {
        private ServerImagingAccess ServerImagingAccess => imagingAccess;

        /// <summary>
        /// Gets the document from imaging.
        /// </summary>
        /// <param name="documentGuid">The document unique identifier.</param>
        /// <param name="documentCategory">Document class.</param>
        /// <returns>The file from imaging</returns>
        [HttpGet("GetDocument/{documentCategory}/{documentGuid:guid}")]
        public async Task<ActionResult> GetDocument(Guid documentGuid, ImagingDocumentCategory documentCategory)
        {
            try
            {
                var (filestream, filename, contentType) = await ServerImagingAccess.GetFileStreamAsync(documentGuid, documentCategory);
                //TODO: Check if imaging system has a file date that can be passed in below as LastModifiedDate
                return new FileStreamResult(filestream, contentType) { FileDownloadName = filename };
            }
            catch (Exception ex)
            {
                loggingService.LogException(ex, "Exception getting document from imaging.", category: "Imaging");
                //TODO:Remove this once unhandled exceptions are handled and logged 
                return new StatusCodeResult(500);
            }
        }

        /// <summary>
        /// Upload a single document
        /// </summary>
        /// <param name="file">The IFormFile to upload</param>
        /// <param name="docType">doctype to upload as</param>
        /// <param name="category">ImagingDocumentCategory cast as an int</param>
        /// <param name="batch">Any meaningful string to identify batch</param>
        /// <param name="filename">Name to save as instead of the original filename</param>
        /// <param name="documentId">DocumentId guid.  Will be autogenerated if not set.</param>
        /// <returns>StatusCodeResult</returns>
        [HttpPost("UploadDocument/{docType}/{category:int}/{id}")] //?documentId={documentId};filename={filename}
        public async Task<ActionResult> UploadDocument(IFormFile file, string docType, int category, string id, string batch = "", [FromQuery] string filename = "", [FromQuery] Guid documentId = new Guid())
        {
            var fileType = filename.Split('.').Last();
            if (!ServerImagingAccess.IsAllowedFileType(fileType))
            {
                loggingService.LogError("Unsupported File type", 
                    "FileType is not supported by the P8 imaging system.  Contact BTS to add this file type if it is needed.", 
                    "Imaging", new Dictionary<string, string>() { { "FileType", fileType } });
                return new StatusCodeResult(422);//Unprocessable content
            }
            if (string.IsNullOrWhiteSpace(batch)) batch = file.FileName;
            
            var guid = await ServerImagingAccess.UploadDocument(docType, string.IsNullOrWhiteSpace(filename)? file.Name:filename, 
                file.OpenReadStream(),
                file.ContentType, (ImagingDocumentCategory)category, 
                id, batch, DateTime.Now);
            var jsonResult = JsonSerializer.Serialize(new { DocumentID = guid });
            //TODO:Handle errors from imaging system
            return new ContentResult{Content = JsonSerializer.Serialize(jsonResult), ContentType = "application/json", StatusCode = 200};
        }

        /// <summary>
        /// Upload multiple documents to imaging
        /// </summary>
        /// <param name="uploadedFiles">Files to upload</param>
        /// <param name="docType">doctype to upload as</param>
        /// <param name="category">ImagingDocumentCategory cast as an int</param>
        /// <param name="batch">Any meaningful string to identify batch</param>
        /// <returns>StatusCodeResult</returns>
        [HttpPost("UploadDocuments/{docType}/{category:int}")]
        public async Task<StatusCodeResult> UploadDocuments(IFormFileCollection uploadedFiles, string docType, int category, string batch="")
        {
            //Pre-validate
            var unsupportedFiles = uploadedFiles
                .Where(uf => ServerImagingAccess.IsAllowedFileType(uf.FileName.Split('.').Last()) == false).ToArray();
            if (unsupportedFiles.Length != 0)
            {
                var errorData =
                    Enumerable.Range(1, unsupportedFiles.Length)
                    .ToDictionary(i =>
                        unsupportedFiles[i].Name, i => unsupportedFiles[i].ContentType);
                loggingService.LogError("Unsupported File type(s)",
                    "A document with an unsupported file type detected.  Contact BTS to add this file type if it is needed.",
                    "Imaging", errorData);
                return new StatusCodeResult(422);//Unprocessable content
            }
            try
            {
                var options = new ParallelOptions() { MaxDegreeOfParallelism = 4 };
                await Parallel.ForEachAsync(uploadedFiles, options, async (uf, ct) => await UploadDocument(uf, docType, category, batch));
                return new StatusCodeResult(200);
            }
            catch (Exception ex)
            {
                loggingService.LogException(ex, "Error uploading files to imaging", category: "Imaging");
                return new StatusCodeResult(500);
                //TODO: remove throw when unhandled exceptions are handled.
                throw;
            }
        }
    }
}
